from _typeshed import Incomplete

__all__ = ['BaseLoader']

class BaseLoader:
    builtin_modules: Incomplete
    configured: bool
    override_backends: Incomplete
    worker_initialized: bool
    app: Incomplete
    task_modules: Incomplete
    def __init__(self, app, **kwargs) -> None: ...
    def now(self, utc: bool = True): ...
    def on_task_init(self, task_id, task) -> None: ...
    def on_process_cleanup(self) -> None: ...
    def on_worker_init(self) -> None: ...
    def on_worker_shutdown(self) -> None: ...
    def on_worker_process_init(self) -> None: ...
    def import_task_module(self, module): ...
    def import_module(self, module, package: Incomplete | None = None): ...
    def import_from_cwd(self, module, imp: Incomplete | None = None, package: Incomplete | None = None): ...
    def import_default_modules(self): ...
    def init_worker(self) -> None: ...
    def shutdown_worker(self) -> None: ...
    def init_worker_process(self) -> None: ...
    def config_from_object(self, obj, silent: bool = False): ...
    def find_module(self, module): ...
    def cmdline_config_parser(self, args, namespace: str = 'celery', re_type=..., extra_types: Incomplete | None = None, override_types: Incomplete | None = None): ...
    def read_configuration(self, env: str = 'CELERY_CONFIG_MODULE'): ...
    def autodiscover_tasks(self, packages, related_name: str = 'tasks') -> None: ...
    def default_modules(self): ...
    @property
    def conf(self): ...
