import abc
from _typeshed import Incomplete
from abc import ABCMeta, abstractmethod
from collections.abc import Callable

__all__ = ['CallableTask', 'CallableSignature']

class _AbstractClass(metaclass=ABCMeta):
    __required_attributes__: Incomplete
    @classmethod
    def register(cls, other): ...

class CallableTask(_AbstractClass, Callable, metaclass=abc.ABCMeta):
    __required_attributes__: Incomplete
    @abstractmethod
    def delay(self, *args, **kwargs): ...
    @abstractmethod
    def apply_async(self, *args, **kwargs): ...
    @abstractmethod
    def apply(self, *args, **kwargs): ...
    @classmethod
    def __subclasshook__(cls, C): ...

class CallableSignature(CallableTask, metaclass=abc.ABCMeta):
    __required_attributes__: Incomplete
    @property
    @abstractmethod
    def name(self): ...
    @property
    @abstractmethod
    def type(self): ...
    @property
    @abstractmethod
    def app(self): ...
    @property
    @abstractmethod
    def id(self): ...
    @property
    @abstractmethod
    def task(self): ...
    @property
    @abstractmethod
    def args(self): ...
    @property
    @abstractmethod
    def kwargs(self): ...
    @property
    @abstractmethod
    def options(self): ...
    @property
    @abstractmethod
    def subtask_type(self): ...
    @property
    @abstractmethod
    def chord_size(self): ...
    @property
    @abstractmethod
    def immutable(self): ...
    @abstractmethod
    def clone(self, args: Incomplete | None = None, kwargs: Incomplete | None = None): ...
    @abstractmethod
    def freeze(self, id: Incomplete | None = None, group_id: Incomplete | None = None, chord: Incomplete | None = None, root_id: Incomplete | None = None, group_index: Incomplete | None = None): ...
    @abstractmethod
    def set(self, immutable: Incomplete | None = None, **options): ...
    @abstractmethod
    def link(self, callback): ...
    @abstractmethod
    def link_error(self, errback): ...
    @abstractmethod
    def __or__(self, other): ...
    @abstractmethod
    def __invert__(self): ...
    @classmethod
    def __subclasshook__(cls, C): ...
