from _typeshed import Incomplete
from collections import OrderedDict as _OrderedDict
from collections.abc import Mapping, MutableMapping
from django.utils.functional import LazyObject
from queue import Empty
from typing import Any, Iterable

__all__ = ['AttributeDictMixin', 'AttributeDict', 'BufferMap', 'ChainMap', 'ConfigurationView', 'DictAttribute', 'Evictable', 'LimitedSet', 'Messagebuffer', 'OrderedDict', 'force_mapping', 'lpmerge']

class LazyObject: ...
LazySettings = LazyObject

def force_mapping(m: Any) -> Mapping: ...
def lpmerge(L: Mapping, R: Mapping) -> Mapping: ...

class OrderedDict(_OrderedDict):
    def move_to_end(self, key: Any, last: bool = True) -> None: ...
    def move_to_end(self, key: Any, last: bool = True) -> None: ...

class AttributeDictMixin:
    def __getattr__(self, k: str) -> Any: ...
    def __setattr__(self, key: str, value) -> None: ...

class AttributeDict(dict, AttributeDictMixin): ...

class DictAttribute:
    obj: Incomplete
    def __init__(self, obj: Any) -> None: ...
    def __getattr__(self, key: Any) -> Any: ...
    def __setattr__(self, key: Any, value: Any) -> None: ...
    def get(self, key: Any, default: Any = None) -> Any: ...
    def setdefault(self, key: Any, default: Any = None) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> Any: ...
    def __contains__(self, key: Any) -> bool: ...
    iterkeys: Incomplete
    def __iter__(self) -> Iterable: ...
    iteritems: Incomplete
    itervalues: Incomplete
    items: Incomplete
    keys: Incomplete
    values: Incomplete

class ChainMap(MutableMapping):
    key_t: Incomplete
    changes: Incomplete
    defaults: Incomplete
    maps: Incomplete
    def __init__(self, *maps: Mapping, **kwargs: Any) -> None: ...
    def add_defaults(self, d: Mapping) -> None: ...
    def pop(self, key: Any, *default: Any) -> Any: ...
    def __missing__(self, key: Any) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def clear(self) -> None: ...
    def get(self, key: Any, default: Any = None) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __contains__(self, key: Any) -> bool: ...
    def __bool__(self) -> bool: ...
    __nonzero__ = __bool__
    def setdefault(self, key: Any, default: Any = None) -> None: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...
    @classmethod
    def fromkeys(cls, iterable: Iterable, *args: Any) -> ChainMap: ...
    def copy(self) -> ChainMap: ...
    __copy__ = copy
    iterkeys: Incomplete
    iteritems: Incomplete
    itervalues: Incomplete
    def bind_to(self, callback) -> None: ...
    keys: Incomplete
    items: Incomplete
    values: Incomplete

class ConfigurationView(ChainMap, AttributeDictMixin):
    def __init__(self, changes: Mapping, defaults: Mapping = None, keys: list[str] = None, prefix: str = None) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> Any: ...
    def first(self, *keys: str) -> Any: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def clear(self) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def swap_with(self, other: ConfigurationView) -> None: ...

class LimitedSet:
    max_heap_percent_overload: int
    maxlen: Incomplete
    minlen: Incomplete
    expires: Incomplete
    def __init__(self, maxlen: int = 0, expires: float = 0, data: Mapping = None, minlen: int = 0) -> None: ...
    def clear(self) -> None: ...
    def add(self, item: Any, now: float = None) -> None: ...
    def update(self, other: Iterable) -> None: ...
    def discard(self, item: Any) -> None: ...
    pop_value = discard
    def purge(self, now: float = None) -> None: ...
    def pop(self, default: Any = None) -> Any: ...
    def as_dict(self) -> dict: ...
    def __eq__(self, other: Any) -> bool: ...
    def __iter__(self) -> Iterable: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: Any) -> bool: ...
    def __reduce__(self) -> Any: ...
    def __bool__(self) -> bool: ...
    __nonzero__ = __bool__

class Evictable:
    Empty = Empty
    def evict(self) -> None: ...

class Messagebuffer(Evictable):
    Empty = Empty
    maxsize: Incomplete
    data: Incomplete
    def __init__(self, maxsize: int, iterable: Iterable = None, deque: Any = ...) -> None: ...
    def put(self, item: Any) -> None: ...
    def extend(self, it: Iterable) -> None: ...
    def take(self, *default: Any) -> Any: ...
    def __iter__(self) -> Iterable: ...
    def __len__(self) -> int: ...
    def __contains__(self, item) -> bool: ...
    def __reversed__(self) -> Iterable: ...
    def __getitem__(self, index: Any) -> Any: ...

class BufferMap(OrderedDict, Evictable):
    Buffer = Messagebuffer
    Empty = Empty
    maxsize: Incomplete
    total: int
    bufmaxsize: Incomplete
    def __init__(self, maxsize: int, iterable: Iterable = None, bufmaxsize: int = 1000) -> None: ...
    def put(self, key: Any, item: Any) -> None: ...
    def extend(self, key: Any, it: Iterable) -> None: ...
    def take(self, key: Any, *default: Any) -> Any: ...
