from _typeshed import Incomplete

__all__ = ['Callable', 'Property', 'warn']

def warn(description: Incomplete | None = None, deprecation: Incomplete | None = None, removal: Incomplete | None = None, alternative: Incomplete | None = None, stacklevel: int = 2) -> None: ...
def Callable(deprecation: Incomplete | None = None, removal: Incomplete | None = None, alternative: Incomplete | None = None, description: Incomplete | None = None): ...
def Property(deprecation: Incomplete | None = None, removal: Incomplete | None = None, alternative: Incomplete | None = None, description: Incomplete | None = None): ...

class _deprecated_property:
    depreinfo: Incomplete
    def __init__(self, fget: Incomplete | None = None, fset: Incomplete | None = None, fdel: Incomplete | None = None, doc: Incomplete | None = None, **depreinfo) -> None: ...
    def __get__(self, obj, type: Incomplete | None = None): ...
    def __set__(self, obj, value): ...
    def __delete__(self, obj): ...
    def setter(self, fset): ...
    def deleter(self, fdel): ...
