from _typeshed import Incomplete
from collections import UserList
from collections.abc import Generator
from kombu.utils.functional import LRUCache as LRUCache, dictfilter as dictfilter, is_list as is_list, lazy as lazy, maybe_evaluate as maybe_evaluate, maybe_list as maybe_list, memoize as memoize
from typing import Any, Callable

__all__ = ['LRUCache', 'is_list', 'maybe_list', 'memoize', 'mlazy', 'noop', 'first', 'firstmethod', 'chunks', 'padlist', 'mattrgetter', 'uniq', 'regen', 'dictfilter', 'lazy', 'maybe_evaluate', 'head_from_fun', 'maybe', 'fun_accepts_kwargs']

class DummyContext:
    def __enter__(self): ...
    def __exit__(self, *exc_info) -> None: ...

class mlazy(lazy):
    evaluated: bool
    def evaluate(self): ...

def noop(*args, **kwargs) -> None: ...
def first(predicate, it): ...
def firstmethod(method, on_call: Incomplete | None = None): ...
def chunks(it, n) -> Generator[Incomplete]: ...
def padlist(container, size, default: Incomplete | None = None): ...
def mattrgetter(*attrs): ...
def uniq(it): ...
def regen(it): ...

class _regen(UserList, list):
    def __init__(self, it) -> None: ...
    def __reduce__(self): ...
    def map(self, func) -> None: ...
    def __length_hint__(self) -> int: ...
    def __iter__(self): ...
    def __getitem__(self, index): ...
    def __bool__(self) -> bool: ...
    @property
    def data(self): ...

def head_from_fun(fun: Callable[..., Any], bound: bool = False) -> str: ...
def fun_accepts_kwargs(fun): ...
def maybe(typ, val): ...
