from _typeshed import Incomplete

__all__ = ['DOT', 'CycleError', 'DependencyGraph', 'GraphFormatter']

class DOT:
    HEAD: Incomplete
    ATTR: str
    NODE: str
    EDGE: str
    ATTRSEP: str
    DIRS: Incomplete
    TAIL: str

class CycleError(Exception): ...

class DependencyGraph:
    formatter: Incomplete
    adjacent: Incomplete
    def __init__(self, it: Incomplete | None = None, formatter: Incomplete | None = None) -> None: ...
    def add_arc(self, obj) -> None: ...
    def add_edge(self, A, B) -> None: ...
    def connect(self, graph) -> None: ...
    def topsort(self): ...
    def valency_of(self, obj): ...
    def update(self, it) -> None: ...
    def edges(self): ...
    def to_dot(self, fh, formatter: Incomplete | None = None) -> None: ...
    def format(self, obj): ...
    def __iter__(self): ...
    def __getitem__(self, node): ...
    def __len__(self) -> int: ...
    def __contains__(self, obj) -> bool: ...
    items: Incomplete
    iteritems: Incomplete
    def repr_node(self, obj, level: int = 1, fmt: str = '{0}({1})'): ...

class GraphFormatter:
    scheme: Incomplete
    edge_scheme: Incomplete
    node_scheme: Incomplete
    term_scheme: Incomplete
    graph_scheme: Incomplete
    id: Incomplete
    root: Incomplete
    type: Incomplete
    direction: Incomplete
    IN: Incomplete
    INp: Incomplete
    def __init__(self, root: Incomplete | None = None, type: Incomplete | None = None, id: Incomplete | None = None, indent: int = 0, inw=..., **scheme) -> None: ...
    def attr(self, name, value): ...
    def attrs(self, d, scheme: Incomplete | None = None): ...
    def head(self, **attrs): ...
    def tail(self): ...
    def label(self, obj): ...
    def node(self, obj, **attrs): ...
    def terminal_node(self, obj, **attrs): ...
    def edge(self, a, b, **attrs): ...
    def FMT(self, fmt, *args, **kwargs): ...
    def draw_edge(self, a, b, scheme: Incomplete | None = None, attrs: Incomplete | None = None): ...
    def draw_node(self, obj, scheme: Incomplete | None = None, attrs: Incomplete | None = None): ...
