from _typeshed import Incomplete
from collections.abc import Generator
from kombu.utils.imports import symbol_by_name as symbol_by_name

__all__ = ['NotAPackage', 'qualname', 'instantiate', 'symbol_by_name', 'cwd_in_path', 'find_module', 'import_from_cwd', 'reload_from_cwd', 'module_file', 'gen_task_name']

class NotAPackage(Exception): ...

def qualname(obj): ...
def instantiate(name, *args, **kwargs): ...
def cwd_in_path() -> Generator[Incomplete]: ...
def find_module(module, path: Incomplete | None = None, imp: Incomplete | None = None): ...
def import_from_cwd(module, imp: Incomplete | None = None, package: Incomplete | None = None): ...
def reload_from_cwd(module, reloader: Incomplete | None = None): ...
def module_file(module): ...
def gen_task_name(app, name, module_name): ...
