import logging
from _typeshed import Incomplete
from collections.abc import Generator
from kombu.log import LOG_LEVELS as LOG_LEVELS
from typing import AnyStr, Sequence

__all__ = ['ColorFormatter', 'LoggingProxy', 'base_logger', 'set_in_sighandler', 'in_sighandler', 'get_logger', 'get_task_logger', 'mlevel', 'get_multiprocessing_logger', 'reset_multiprocessing_logger', 'LOG_LEVELS']

base_logger: Incomplete
def set_in_sighandler(value) -> None: ...
def in_sighandler() -> Generator[None]: ...
def get_logger(name): ...
def get_task_logger(name): ...
def mlevel(level): ...

class ColorFormatter(logging.Formatter):
    COLORS: Incomplete
    colors: Incomplete
    use_color: Incomplete
    def __init__(self, fmt: Incomplete | None = None, use_color: bool = True) -> None: ...
    def formatException(self, ei): ...
    def format(self, record): ...

class LoggingProxy:
    mode: str
    name: Incomplete
    closed: bool
    loglevel: Incomplete
    logger: Incomplete
    def __init__(self, logger, loglevel: Incomplete | None = None) -> None: ...
    def write(self, data: AnyStr) -> int: ...
    def writelines(self, sequence: Sequence[str]) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def isatty(self): ...

def get_multiprocessing_logger(): ...
def reset_multiprocessing_logger() -> None: ...
