from _typeshed import Incomplete
from kombu.entity import Queue

__all__ = ['worker_direct', 'gethostname', 'nodename', 'anon_nodename', 'nodesplit', 'default_nodename', 'node_format', 'host_format']

gethostname: Incomplete

def worker_direct(hostname: str | Queue) -> Queue: ...
def nodename(name: str, hostname: str) -> str: ...
def anon_nodename(hostname: str | None = None, prefix: str = 'gen') -> str: ...
def nodesplit(name: str) -> tuple[None, str] | list[str]: ...
def default_nodename(hostname: str) -> str: ...
def node_format(s: str, name: str, **extra: dict) -> str: ...
def host_format(s: str, host: str | None = None, name: str | None = None, **extra: dict) -> str: ...
