from _typeshed import Incomplete

__all__ = ['Bunch', 'FallbackContext', 'getitem_property', 'mro_lookup']

class Bunch:
    def __init__(self, **kwargs) -> None: ...

def mro_lookup(cls, attr, stop: Incomplete | None = None, monkey_patched: Incomplete | None = None): ...

class FallbackContext:
    provided: Incomplete
    fallback: Incomplete
    fb_args: Incomplete
    fb_kwargs: Incomplete
    def __init__(self, provided, fallback, *fb_args, **fb_kwargs) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc_info): ...

class getitem_property:
    path: Incomplete
    __doc__: Incomplete
    def __init__(self, keypath, doc: Incomplete | None = None) -> None: ...
    def __get__(self, obj, type: Incomplete | None = None): ...
    def __set__(self, obj, value) -> None: ...
