from _typeshed import Incomplete

__all__ = ['UnpickleableExceptionWrapper', 'subclass_exception', 'find_pickleable_exception', 'create_exception_cls', 'get_pickleable_exception', 'get_pickleable_etype', 'get_pickled_exception', 'strtobool']

def subclass_exception(name, parent, module): ...
def find_pickleable_exception(exc, loads=..., dumps=...): ...
def create_exception_cls(name, module, parent: Incomplete | None = None): ...

class UnpickleableExceptionWrapper(Exception):
    exc_module: Incomplete
    exc_cls_name: Incomplete
    exc_args: Incomplete
    text: Incomplete
    def __init__(self, exc_module, exc_cls_name, exc_args, text: Incomplete | None = None) -> None: ...
    def restore(self): ...
    @classmethod
    def from_exception(cls, exc): ...

def get_pickleable_exception(exc): ...
def get_pickleable_etype(cls, loads=..., dumps=...): ...
def get_pickled_exception(exc): ...
def strtobool(term, table: Incomplete | None = None): ...
