import os
from _typeshed import Incomplete

__all__ = ['load_average', 'df']

def load_average() -> tuple[float, ...]: ...

class df:
    path: Incomplete
    def __init__(self, path: str | bytes | os.PathLike) -> None: ...
    @property
    def total_blocks(self) -> float: ...
    @property
    def available(self) -> float: ...
    @property
    def capacity(self) -> int: ...
    def stat(self) -> os.statvfs_result: ...
