from _typeshed import Incomplete
from typing import Any, Callable, Pattern

__all__ = ['abbr', 'abbrtask', 'dedent', 'dedent_initial', 'ensure_newlines', 'ensure_sep', 'fill_paragraphs', 'indent', 'join', 'pluralize', 'pretty', 'str_to_list', 'simple_format', 'truncate']

def str_to_list(s: str) -> list[str]: ...
def dedent_initial(s: str, n: int = 4) -> str: ...
def dedent(s: str, sep: str = '\n') -> str: ...
def fill_paragraphs(s: str, width: int, sep: str = '\n') -> str: ...
def join(l: list[str], sep: str = '\n') -> str: ...
def ensure_sep(sep: str, s: str, n: int = 2) -> str: ...

ensure_newlines: Incomplete

def abbr(S: str, max: int, ellipsis: str | bool = '...') -> str: ...
def abbrtask(S: str, max: int) -> str: ...
def indent(t: str, indent: int = 0, sep: str = '\n') -> str: ...
def truncate(s: str, maxlen: int = 128, suffix: str = '...') -> str: ...
def pluralize(n: float, text: str, suffix: str = 's') -> str: ...
def pretty(value: str, width: int = 80, nl_width: int = 80, sep: str = '\n', **kw: Any) -> str: ...
def simple_format(s: str, keys: dict[str, str | Callable], pattern: Pattern[str] = ..., expand: str = '\\1') -> str: ...

class WhateverIO(StringIO):
    def __init__(self, v: bytes | str | None = None, *a: Any, **kw: Any) -> None: ...
    def write(self, data: bytes | str) -> int: ...
