import threading
from _typeshed import Incomplete
from collections.abc import Generator
from dummy_thread import get_ident as get_ident

__all__ = ['bgThread', 'Local', 'LocalStack', 'LocalManager', 'get_ident', 'default_socket_timeout']

def default_socket_timeout(timeout) -> Generator[None]: ...

class bgThread(threading.Thread):
    daemon: bool
    name: Incomplete
    def __init__(self, name: Incomplete | None = None, **kwargs) -> None: ...
    def body(self) -> None: ...
    def on_crash(self, msg, *fmt, **kwargs) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...

class Local:
    def __init__(self) -> None: ...
    def __iter__(self): ...
    def __call__(self, proxy): ...
    def __release_local__(self) -> None: ...
    def __getattr__(self, name): ...
    def __setattr__(self, name, value) -> None: ...
    def __delattr__(self, name) -> None: ...

class _LocalStack:
    def __init__(self) -> None: ...
    def __release_local__(self) -> None: ...
    __ident_func__: Incomplete
    def __call__(self): ...
    def push(self, obj): ...
    def pop(self): ...
    def __len__(self) -> int: ...
    @property
    def stack(self): ...
    @property
    def top(self): ...

class LocalManager:
    locals: Incomplete
    ident_func: Incomplete
    def __init__(self, locals: Incomplete | None = None, ident_func: Incomplete | None = None) -> None: ...
    def get_ident(self): ...
    def cleanup(self) -> None: ...

class _FastLocalStack(threading.local):
    stack: Incomplete
    push: Incomplete
    pop: Incomplete
    def __init__(self) -> None: ...
    @property
    def top(self): ...
    def __len__(self) -> int: ...

LocalStack: Incomplete
