import threading
from _typeshed import Incomplete
from kombu.asynchronous.timer import Entry as Entry, Timer as Schedule, to_timestamp as to_timestamp

__all__ = ['Entry', 'Schedule', 'Timer', 'to_timestamp']

class Timer(threading.Thread):
    Entry = Entry
    Schedule = Schedule
    running: bool
    on_tick: Incomplete
    def start(self, *args, **kwargs) -> None: ...
    schedule: Incomplete
    on_start: Incomplete
    mutex: Incomplete
    not_empty: Incomplete
    daemon: bool
    name: Incomplete
    def __init__(self, schedule: Incomplete | None = None, on_error: Incomplete | None = None, on_tick: Incomplete | None = None, on_start: Incomplete | None = None, max_interval: Incomplete | None = None, **kwargs) -> None: ...
    __next__: Incomplete
    next: Incomplete
    scheduler: Incomplete
    def run(self) -> None: ...
    def stop(self) -> None: ...
    def ensure_started(self) -> None: ...
    def enter(self, entry, eta, priority: Incomplete | None = None): ...
    def call_at(self, *args, **kwargs): ...
    def enter_after(self, *args, **kwargs): ...
    def call_after(self, *args, **kwargs): ...
    def call_repeatedly(self, *args, **kwargs): ...
    def exit_after(self, secs, priority: int = 10) -> None: ...
    def cancel(self, tref) -> None: ...
    def clear(self) -> None: ...
    def empty(self): ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    __nonzero__ = __bool__
    @property
    def queue(self): ...
