import time as _time
from _typeshed import Incomplete
from datetime import datetime, timedelta, tzinfo
from types import ModuleType
from typing import Any, Callable

__all__ = ['LocalTimezone', 'timezone', 'maybe_timedelta', 'delta_resolution', 'remaining', 'rate', 'weekday', 'humanize_seconds', 'maybe_iso8601', 'is_naive', 'make_aware', 'localize', 'to_utc', 'maybe_make_aware', 'ffwd', 'utcoffset', 'adjust_timestamp', 'get_exponential_backoff_interval']

class LocalTimezone(tzinfo):
    STDOFFSET: Incomplete
    DSTOFFSET: Incomplete
    DSTDIFF: Incomplete
    def __init__(self) -> None: ...
    def utcoffset(self, dt: datetime) -> timedelta: ...
    def dst(self, dt: datetime) -> timedelta: ...
    def tzname(self, dt: datetime) -> str: ...
    def fromutc(self, dt: datetime) -> datetime: ...

class _Zone:
    def tz_or_local(self, tzinfo: tzinfo | None = None) -> tzinfo: ...
    def to_local(self, dt: datetime, local: Incomplete | None = None, orig: Incomplete | None = None): ...
    def to_system(self, dt: datetime) -> datetime: ...
    def to_local_fallback(self, dt: datetime) -> datetime: ...
    def get_timezone(self, zone: str | tzinfo) -> tzinfo: ...
    def local(self) -> LocalTimezone: ...
    def utc(self) -> tzinfo: ...

timezone: Incomplete

def maybe_timedelta(delta: int) -> timedelta: ...
def delta_resolution(dt: datetime, delta: timedelta) -> datetime: ...
def remaining(start: datetime, ends_in: timedelta, now: Callable | None = None, relative: bool = False) -> timedelta: ...
def rate(r: str) -> float: ...
def weekday(name: str) -> int: ...
def humanize_seconds(secs: int, prefix: str = '', sep: str = '', now: str = 'now', microseconds: bool = False) -> str: ...
def maybe_iso8601(dt: datetime | str | None) -> None | datetime: ...
def is_naive(dt: datetime) -> bool: ...
def make_aware(dt: datetime, tz: tzinfo) -> datetime: ...
def localize(dt: datetime, tz: tzinfo) -> datetime: ...
def to_utc(dt: datetime) -> datetime: ...
def maybe_make_aware(dt: datetime, tz: tzinfo | None = None, naive_as_utc: bool = True) -> datetime: ...

class ffwd:
    year: Incomplete
    month: Incomplete
    weeks: Incomplete
    weekday: Incomplete
    day: Incomplete
    hour: Incomplete
    minute: Incomplete
    second: Incomplete
    microsecond: Incomplete
    days: Incomplete
    def __init__(self, year: Incomplete | None = None, month: Incomplete | None = None, weeks: int = 0, weekday: Incomplete | None = None, day: Incomplete | None = None, hour: Incomplete | None = None, minute: Incomplete | None = None, second: Incomplete | None = None, microsecond: Incomplete | None = None, **kwargs: Any) -> None: ...
    def __radd__(self, other: Any) -> timedelta: ...

def utcoffset(time: ModuleType = ..., localtime: Callable[..., _time.struct_time] = ...) -> float: ...
def adjust_timestamp(ts: float, offset: int, here: Callable[..., float] = ...) -> float: ...
def get_exponential_backoff_interval(factor: int, retries: int, maximum: int, full_jitter: bool = False) -> int: ...
