systemLog:
    destination: file
    path: "logs/mongodb.log"
    logAppend: true
processManagement:
    fork: false
    pidFilePath: "db/mongod.pid"
net:
    bindIp: localhost,db/general.sock
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: "db/"
setParameter:
    enableLocalhostAuthBypass: false
storage:
    dbPath: "db/data/"
