import threading
from _typeshed import Incomplete

__all__ = ['CursesMonitor', 'evtop']

class CursesMonitor:
    keymap: Incomplete
    win: Incomplete
    screen_delay: int
    selected_task: Incomplete
    selected_position: int
    selected_str: str
    foreground: Incomplete
    background: Incomplete
    online_str: str
    help_title: str
    help: str
    greet: Incomplete
    info_str: str
    app: Incomplete
    state: Incomplete
    lock: Incomplete
    def __init__(self, state, app, keymap: Incomplete | None = None) -> None: ...
    def format_row(self, uuid, task, worker, timestamp, state): ...
    @property
    def screen_width(self): ...
    @property
    def screen_height(self): ...
    @property
    def display_width(self): ...
    @property
    def display_height(self): ...
    @property
    def limit(self): ...
    def find_position(self): ...
    def move_selection_up(self) -> None: ...
    def move_selection_down(self) -> None: ...
    def move_selection(self, direction: int = 1) -> None: ...
    keyalias: Incomplete
    def handle_keypress(self) -> None: ...
    def alert(self, callback, title: Incomplete | None = None): ...
    def selection_rate_limit(self): ...
    def alert_remote_control_reply(self, reply): ...
    def readline(self, x, y): ...
    def revoke_selection(self): ...
    def selection_info(self): ...
    def selection_traceback(self): ...
    def selection_result(self): ...
    def display_task_row(self, lineno, task) -> None: ...
    def draw(self) -> None: ...
    def safe_add_str(self, y, x, string, *args, **kwargs) -> None: ...
    state_colors: Incomplete
    def init_screen(self) -> None: ...
    def resetscreen(self) -> None: ...
    def nap(self) -> None: ...
    @property
    def tasks(self): ...
    @property
    def workers(self): ...

class DisplayThread(threading.Thread):
    display: Incomplete
    shutdown: bool
    def __init__(self, display) -> None: ...
    def run(self) -> None: ...

def evtop(app: Incomplete | None = None) -> None: ...
