from _typeshed import Incomplete
from kombu.mixins import ConsumerMixin

__all__ = ['EventReceiver']

class EventReceiver(ConsumerMixin):
    app: Incomplete
    channel: Incomplete
    handlers: Incomplete
    routing_key: Incomplete
    node_id: Incomplete
    queue_prefix: Incomplete
    exchange: Incomplete
    queue: Incomplete
    clock: Incomplete
    adjust_clock: Incomplete
    forward_clock: Incomplete
    accept: Incomplete
    def __init__(self, channel, handlers: Incomplete | None = None, routing_key: str = '#', node_id: Incomplete | None = None, app: Incomplete | None = None, queue_prefix: Incomplete | None = None, accept: Incomplete | None = None, queue_ttl: Incomplete | None = None, queue_expires: Incomplete | None = None) -> None: ...
    def process(self, type, event) -> None: ...
    def get_consumers(self, Consumer, channel): ...
    def on_consume_ready(self, connection, channel, consumers, wakeup: bool = True, **kwargs) -> None: ...
    def itercapture(self, limit: Incomplete | None = None, timeout: Incomplete | None = None, wakeup: bool = True): ...
    def capture(self, limit: Incomplete | None = None, timeout: Incomplete | None = None, wakeup: bool = True) -> None: ...
    def wakeup_workers(self, channel: Incomplete | None = None) -> None: ...
    def event_from_message(self, body, localize: bool = True, now=..., tzfields=..., adjust_timestamp=..., CLIENT_CLOCK_SKEW=...): ...
    @property
    def connection(self): ...
