from _typeshed import Incomplete

__all__ = ['Polaroid', 'evcam']

class Polaroid:
    timer: Incomplete
    shutter_signal: Incomplete
    cleanup_signal: Incomplete
    clear_after: bool
    app: Incomplete
    state: Incomplete
    freq: Incomplete
    cleanup_freq: Incomplete
    logger: Incomplete
    maxrate: Incomplete
    def __init__(self, state, freq: float = 1.0, maxrate: Incomplete | None = None, cleanup_freq: float = 3600.0, timer: Incomplete | None = None, app: Incomplete | None = None) -> None: ...
    def install(self) -> None: ...
    def on_shutter(self, state) -> None: ...
    def on_cleanup(self) -> None: ...
    def cleanup(self) -> None: ...
    def shutter(self) -> None: ...
    def capture(self) -> None: ...
    def cancel(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc_info) -> None: ...

def evcam(camera, freq: float = 1.0, maxrate: Incomplete | None = None, loglevel: int = 0, logfile: Incomplete | None = None, pidfile: Incomplete | None = None, timer: Incomplete | None = None, app: Incomplete | None = None, **kwargs) -> None: ...
