from _typeshed import Incomplete
from celery.app.base import Celery
from celery.app.task import Task
from datetime import datetime
from django.db.utils import ConnectionHandler
from typing import Any, Protocol

__all__ = ['DjangoFixup', 'fixup']

class DjangoDBModule(Protocol):
    connections: ConnectionHandler

def fixup(app: Celery, env: str = 'DJANGO_SETTINGS_MODULE') -> DjangoFixup | None: ...

class DjangoFixup:
    app: Incomplete
    def __init__(self, app: Celery) -> None: ...
    def install(self) -> DjangoFixup: ...
    @property
    def worker_fixup(self) -> DjangoWorkerFixup: ...
    @worker_fixup.setter
    def worker_fixup(self, value: DjangoWorkerFixup) -> None: ...
    def on_import_modules(self, **kwargs: Any) -> None: ...
    def on_worker_init(self, **kwargs: Any) -> None: ...
    def now(self, utc: bool = False) -> datetime: ...
    def autodiscover_tasks(self) -> list[str]: ...

class DjangoWorkerFixup:
    app: Incomplete
    db_reuse_max: Incomplete
    interface_errors: Incomplete
    DatabaseError: Incomplete
    def __init__(self, app: Celery) -> None: ...
    def django_setup(self) -> None: ...
    def validate_models(self) -> None: ...
    def install(self) -> DjangoWorkerFixup: ...
    def on_worker_process_init(self, **kwargs: Any) -> None: ...
    def on_task_prerun(self, sender: Task, **kwargs: Any) -> None: ...
    def on_task_postrun(self, sender: Task, **kwargs: Any) -> None: ...
    def close_database(self, **kwargs: Any) -> None: ...
    def close_cache(self) -> None: ...
