# Generated by Django 5.1.6 on 2025-03-04 18:10

import apps.optics.models
import django.utils.timezone
import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('usage_count', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('override_rate', models.FloatField(default=0.0)),
                ('avg_edit_distance', models.FloatField(default=0.0)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('merchant_name', models.CharField(max_length=255)),
                ('currency_info', djongo.models.fields.JSONField(default=dict, validators=[apps.optics.models.validate_currency_info])),
                ('field_extractors', djongo.models.fields.JSONField(default=dict, validators=[apps.optics.models.validate_field_extractors])),
                ('has_line_items', models.BooleanField(default=True)),
                ('line_items_start_line', models.IntegerField(default=5)),
                ('item_patterns', djongo.models.fields.JSONField(default=list, validators=[apps.optics.models.validate_item_patterns])),
                ('field_accuracy', djongo.models.fields.JSONField(default=dict, validators=[apps.optics.models.validate_field_accuracy])),
                ('field_edit_distances', djongo.models.fields.JSONField(default=dict, validators=[apps.optics.models.validate_field_edit_distances])),
                ('recent_usage', djongo.models.fields.JSONField(default=dict, validators=[apps.optics.models.validate_recent_usage])),
            ],
            options={
                'db_table': 'receipt_templates',
                'indexes': [models.Index(fields=['merchant_name'], name='receipt_tem_merchan_2a8673_idx'), models.Index(fields=['is_archived'], name='receipt_tem_is_arch_155002_idx'), models.Index(fields=['last_used_at'], name='receipt_tem_last_us_57624d_idx')],
            },
        ),
    ]
