from _typeshed import Incomplete

__all__ = ['StopFiltering', 'State', 'republish', 'migrate_task', 'migrate_tasks', 'move', 'task_id_eq', 'task_id_in', 'start_filter', 'move_task_by_id', 'move_by_idmap', 'move_by_taskmap', 'move_direct', 'move_direct_by_id']

class StopFiltering(Exception): ...

class State:
    count: int
    filtered: int
    total_apx: int
    @property
    def strtotal(self): ...

def republish(producer, message, exchange: Incomplete | None = None, routing_key: Incomplete | None = None, remove_props: Incomplete | None = None) -> None: ...
def migrate_task(producer, body_, message, queues: Incomplete | None = None) -> None: ...
def migrate_tasks(source, dest, migrate=..., app: Incomplete | None = None, queues: Incomplete | None = None, **kwargs): ...
def move(predicate, connection: Incomplete | None = None, exchange: Incomplete | None = None, routing_key: Incomplete | None = None, source: Incomplete | None = None, app: Incomplete | None = None, callback: Incomplete | None = None, limit: Incomplete | None = None, transform: Incomplete | None = None, **kwargs): ...
def task_id_eq(task_id, body, message): ...
def task_id_in(ids, body, message): ...

class Filterer:
    app: Incomplete
    conn: Incomplete
    filter: Incomplete
    limit: Incomplete
    timeout: Incomplete
    ack_messages: Incomplete
    tasks: Incomplete
    queues: Incomplete
    callback: Incomplete
    forever: Incomplete
    on_declare_queue: Incomplete
    consume_from: Incomplete
    state: Incomplete
    accept: Incomplete
    def __init__(self, app, conn, filter, limit: Incomplete | None = None, timeout: float = 1.0, ack_messages: bool = False, tasks: Incomplete | None = None, queues: Incomplete | None = None, callback: Incomplete | None = None, forever: bool = False, on_declare_queue: Incomplete | None = None, consume_from: Incomplete | None = None, state: Incomplete | None = None, accept: Incomplete | None = None, **kwargs) -> None: ...
    def start(self): ...
    def update_state(self, body, message) -> None: ...
    def ack_message(self, body, message) -> None: ...
    def create_consumer(self): ...
    def prepare_consumer(self, consumer): ...
    def declare_queues(self, consumer) -> None: ...

def start_filter(app, conn, filter, limit: Incomplete | None = None, timeout: float = 1.0, ack_messages: bool = False, tasks: Incomplete | None = None, queues: Incomplete | None = None, callback: Incomplete | None = None, forever: bool = False, on_declare_queue: Incomplete | None = None, consume_from: Incomplete | None = None, state: Incomplete | None = None, accept: Incomplete | None = None, **kwargs): ...
def move_task_by_id(task_id, dest, **kwargs): ...
def move_by_idmap(map, **kwargs): ...
def move_by_taskmap(map, **kwargs): ...

move_direct: Incomplete
move_direct_by_id: Incomplete
