from ..worker import WorkController as WorkController
from _typeshed import Incomplete
from celery import Celery as Celery
from collections.abc import Generator
from typing import Any, Mapping, Sequence

NO_WORKER: Incomplete

def pytest_configure(config) -> None: ...
def use_celery_app_trap() -> bool: ...
def celery_session_app(request: Any, celery_config: Any, celery_parameters: Any, celery_enable_logging: Any, use_celery_app_trap: Any) -> Celery: ...
def celery_session_worker(request: Any, celery_session_app: Celery, celery_includes: Sequence[str], celery_class_tasks: str, celery_worker_pool: Any, celery_worker_parameters: Mapping[str, Any]) -> WorkController: ...
def celery_enable_logging() -> bool: ...
def celery_includes() -> Sequence[str]: ...
def celery_worker_pool() -> str | Any: ...
def celery_config() -> Mapping[str, Any]: ...
def celery_parameters() -> Mapping[str, Any]: ...
def celery_worker_parameters() -> Mapping[str, Any]: ...
def celery_app(request, celery_config, celery_parameters, celery_enable_logging, use_celery_app_trap) -> Generator[Incomplete]: ...
def celery_class_tasks(): ...
def celery_worker(request: Any, celery_app: Celery, celery_includes: Sequence[str], celery_worker_pool: str, celery_worker_parameters: Any) -> WorkController: ...
def depends_on_current_app(celery_app) -> None: ...
