from _typeshed import Incomplete
from pdb import Pdb

__all__ = ['CELERY_RDB_HOST', 'CELERY_RDB_PORT', 'DEFAULT_PORT', 'Rdb', 'debugger', 'set_trace']

DEFAULT_PORT: int
CELERY_RDB_HOST: Incomplete
CELERY_RDB_PORT: Incomplete

class Rdb(Pdb):
    me: str
    active: bool
    out: Incomplete
    ident: Incomplete
    host: Incomplete
    port: Incomplete
    remote_addr: Incomplete
    def __init__(self, host=..., port=..., port_search_limit: int = 100, port_skew: int = +0, out=...) -> None: ...
    def get_avail_port(self, host, port, search_limit: int = 100, skew: int = +0): ...
    def say(self, m) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc_info) -> None: ...
    def do_continue(self, arg): ...
    do_c = do_continue
    do_cont = do_continue
    def do_quit(self, arg): ...
    do_q = do_quit
    do_exit = do_quit
    def set_quit(self) -> None: ...

def debugger(): ...
def set_trace(frame: Incomplete | None = None): ...
