from celery.app.task import BaseTask as BaseTask
from sphinx.domains.python import PyFunction
from sphinx.ext.autodoc import FunctionDocumenter

class TaskDocumenter(FunctionDocumenter):
    objtype: str
    member_order: int
    @classmethod
    def can_document_member(cls, member, membername, isattr, parent): ...
    def format_args(self): ...
    def document_members(self, all_members: bool = False) -> None: ...
    def check_module(self): ...

class TaskDirective(PyFunction):
    def get_signature_prefix(self, sig): ...

def autodoc_skip_member_handler(app, what, name, obj, skip, options): ...
def setup(app): ...
