from _typeshed import Incomplete
from kombu import Connection, Consumer, Producer
from typing import NamedTuple

__all__ = ['AMQP', 'Queues', 'task_message']

class task_message(NamedTuple):
    headers: Incomplete
    properties: Incomplete
    body: Incomplete
    sent_event: Incomplete

class Queues(dict):
    aliases: Incomplete
    default_exchange: Incomplete
    default_routing_key: Incomplete
    create_missing: Incomplete
    autoexchange: Incomplete
    max_priority: Incomplete
    def __init__(self, queues: Incomplete | None = None, default_exchange: Incomplete | None = None, create_missing: bool = True, autoexchange: Incomplete | None = None, max_priority: Incomplete | None = None, default_routing_key: Incomplete | None = None) -> None: ...
    def __getitem__(self, name): ...
    def __setitem__(self, name, queue) -> None: ...
    def __missing__(self, name): ...
    def add(self, queue, **kwargs): ...
    def add_compat(self, name, **options): ...
    def format(self, indent: int = 0, indent_first: bool = True): ...
    def select_add(self, queue, **kwargs): ...
    def select(self, include) -> None: ...
    def deselect(self, exclude): ...
    def new_missing(self, name): ...
    @property
    def consume_from(self): ...

class AMQP:
    Connection = Connection
    Consumer = Consumer
    Producer = Producer
    BrokerConnection = Connection
    queues_cls = Queues
    autoexchange: Incomplete
    argsrepr_maxsize: int
    kwargsrepr_maxsize: int
    app: Incomplete
    task_protocols: Incomplete
    def __init__(self, app) -> None: ...
    def create_task_message(self): ...
    def send_task_message(self): ...
    def Queues(self, queues, create_missing: Incomplete | None = None, autoexchange: Incomplete | None = None, max_priority: Incomplete | None = None): ...
    def Router(self, queues: Incomplete | None = None, create_missing: Incomplete | None = None): ...
    def flush_routes(self) -> None: ...
    def TaskConsumer(self, channel, queues: Incomplete | None = None, accept: Incomplete | None = None, **kw): ...
    def as_task_v2(self, task_id, name, args: Incomplete | None = None, kwargs: Incomplete | None = None, countdown: Incomplete | None = None, eta: Incomplete | None = None, group_id: Incomplete | None = None, group_index: Incomplete | None = None, expires: Incomplete | None = None, retries: int = 0, chord: Incomplete | None = None, callbacks: Incomplete | None = None, errbacks: Incomplete | None = None, reply_to: Incomplete | None = None, time_limit: Incomplete | None = None, soft_time_limit: Incomplete | None = None, create_sent_event: bool = False, root_id: Incomplete | None = None, parent_id: Incomplete | None = None, shadow: Incomplete | None = None, chain: Incomplete | None = None, now: Incomplete | None = None, timezone: Incomplete | None = None, origin: Incomplete | None = None, ignore_result: bool = False, argsrepr: Incomplete | None = None, kwargsrepr: Incomplete | None = None, stamped_headers: Incomplete | None = None, replaced_task_nesting: int = 0, **options): ...
    def as_task_v1(self, task_id, name, args: Incomplete | None = None, kwargs: Incomplete | None = None, countdown: Incomplete | None = None, eta: Incomplete | None = None, group_id: Incomplete | None = None, group_index: Incomplete | None = None, expires: Incomplete | None = None, retries: int = 0, chord: Incomplete | None = None, callbacks: Incomplete | None = None, errbacks: Incomplete | None = None, reply_to: Incomplete | None = None, time_limit: Incomplete | None = None, soft_time_limit: Incomplete | None = None, create_sent_event: bool = False, root_id: Incomplete | None = None, parent_id: Incomplete | None = None, shadow: Incomplete | None = None, now: Incomplete | None = None, timezone: Incomplete | None = None, **compat_kwargs): ...
    def default_queue(self): ...
    @property
    def routes(self): ...
    @property
    def producer_pool(self): ...
    publisher_pool = producer_pool
    def default_exchange(self): ...
    def utc(self): ...

# Names in __all__ with no definition:
#   task_message
