__all__ = ['MapAnnotation', 'prepare', 'resolve_all']

class MapAnnotation(dict):
    def annotate_any(self): ...
    def annotate(self, task): ...

def prepare(annotations): ...
def resolve_all(anno, task): ...
