from .utils import AppPickler
from _typeshed import Incomplete
from celery.utils.collections import AttributeDictMixin
from collections import UserDict

__all__ = ['Celery']

class PendingConfiguration(UserDict, AttributeDictMixin):
    callback: Incomplete
    def __init__(self, conf, callback) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def clear(self) -> None: ...
    def update(self, *args, **kwargs) -> None: ...
    def setdefault(self, *args, **kwargs): ...
    def __contains__(self, key) -> bool: ...
    def __len__(self) -> int: ...
    def data(self): ...

class Celery:
    Pickler = AppPickler
    SYSTEM: Incomplete
    IS_macOS: Incomplete
    IS_WINDOWS: Incomplete
    main: Incomplete
    user_options: Incomplete
    steps: Incomplete
    builtin_fixups = BUILTIN_FIXUPS
    amqp_cls: str
    backend_cls: Incomplete
    events_cls: str
    loader_cls: Incomplete
    log_cls: str
    control_cls: str
    task_cls: str
    registry_cls: str
    on_configure: Incomplete
    on_after_configure: Incomplete
    on_after_finalize: Incomplete
    on_after_fork: Incomplete
    clock: Incomplete
    set_as_current: Incomplete
    autofinalize: Incomplete
    namespace: Incomplete
    strict_typing: Incomplete
    configured: bool
    finalized: bool
    fixups: Incomplete
    use_fast_trace_task: bool
    def __init__(self, main: Incomplete | None = None, loader: Incomplete | None = None, backend: Incomplete | None = None, amqp: Incomplete | None = None, events: Incomplete | None = None, log: Incomplete | None = None, control: Incomplete | None = None, set_as_current: bool = True, tasks: Incomplete | None = None, broker: Incomplete | None = None, include: Incomplete | None = None, changes: Incomplete | None = None, config_source: Incomplete | None = None, fixups: Incomplete | None = None, task_cls: Incomplete | None = None, autofinalize: bool = True, namespace: Incomplete | None = None, strict_typing: bool = True, **kwargs) -> None: ...
    def on_init(self) -> None: ...
    def set_current(self) -> None: ...
    def set_default(self) -> None: ...
    def close(self) -> None: ...
    def start(self, argv: Incomplete | None = None): ...
    def worker_main(self, argv: Incomplete | None = None) -> None: ...
    def task(self, *args, **opts): ...
    def type_checker(self, fun, bound: bool = False): ...
    def register_task(self, task, **options): ...
    def gen_task_name(self, name, module): ...
    def finalize(self, auto: bool = False) -> None: ...
    def add_defaults(self, fun): ...
    def config_from_object(self, obj, silent: bool = False, force: bool = False, namespace: Incomplete | None = None): ...
    def config_from_envvar(self, variable_name, silent: bool = False, force: bool = False): ...
    def config_from_cmdline(self, argv, namespace: str = 'celery') -> None: ...
    def setup_security(self, allowed_serializers: Incomplete | None = None, key: Incomplete | None = None, key_password: Incomplete | None = None, cert: Incomplete | None = None, store: Incomplete | None = None, digest=..., serializer: str = 'json'): ...
    def autodiscover_tasks(self, packages: Incomplete | None = None, related_name: str = 'tasks', force: bool = False): ...
    def send_task(self, name, args: Incomplete | None = None, kwargs: Incomplete | None = None, countdown: Incomplete | None = None, eta: Incomplete | None = None, task_id: Incomplete | None = None, producer: Incomplete | None = None, connection: Incomplete | None = None, router: Incomplete | None = None, result_cls: Incomplete | None = None, expires: Incomplete | None = None, publisher: Incomplete | None = None, link: Incomplete | None = None, link_error: Incomplete | None = None, add_to_parent: bool = True, group_id: Incomplete | None = None, group_index: Incomplete | None = None, retries: int = 0, chord: Incomplete | None = None, reply_to: Incomplete | None = None, time_limit: Incomplete | None = None, soft_time_limit: Incomplete | None = None, root_id: Incomplete | None = None, parent_id: Incomplete | None = None, route_name: Incomplete | None = None, shadow: Incomplete | None = None, chain: Incomplete | None = None, task_type: Incomplete | None = None, replaced_task_nesting: int = 0, **options): ...
    def connection_for_read(self, url: Incomplete | None = None, **kwargs): ...
    def connection_for_write(self, url: Incomplete | None = None, **kwargs): ...
    def connection(self, hostname: Incomplete | None = None, userid: Incomplete | None = None, password: Incomplete | None = None, virtual_host: Incomplete | None = None, port: Incomplete | None = None, ssl: Incomplete | None = None, connect_timeout: Incomplete | None = None, transport: Incomplete | None = None, transport_options: Incomplete | None = None, heartbeat: Incomplete | None = None, login_method: Incomplete | None = None, failover_strategy: Incomplete | None = None, **kwargs): ...
    broker_connection = connection
    def connection_or_acquire(self, connection: Incomplete | None = None, pool: bool = True, *_, **__): ...
    default_connection = connection_or_acquire
    def producer_or_acquire(self, producer: Incomplete | None = None): ...
    default_producer = producer_or_acquire
    def prepare_config(self, c): ...
    def now(self): ...
    def select_queues(self, queues: Incomplete | None = None): ...
    def either(self, default_key, *defaults): ...
    def bugreport(self): ...
    def signature(self, *args, **kwargs): ...
    def add_periodic_task(self, schedule, sig, args=(), kwargs=(), name: Incomplete | None = None, **opts): ...
    def create_task_cls(self): ...
    def subclass_with_self(self, Class, name: Incomplete | None = None, attribute: str = 'app', reverse: Incomplete | None = None, keep_reduce: bool = False, **kw): ...
    def __enter__(self): ...
    def __exit__(self, *exc_info) -> None: ...
    def __reduce__(self): ...
    def __reduce_v1__(self): ...
    def __reduce_keys__(self): ...
    def __reduce_args__(self): ...
    def Worker(self): ...
    def WorkController(self, **kwargs): ...
    def Beat(self, **kwargs): ...
    def Task(self): ...
    def annotations(self): ...
    def AsyncResult(self): ...
    def ResultSet(self): ...
    def GroupResult(self): ...
    @property
    def pool(self): ...
    @property
    def current_task(self): ...
    @property
    def current_worker_task(self): ...
    def oid(self): ...
    @property
    def thread_oid(self): ...
    def amqp(self): ...
    @property
    def backend(self): ...
    @property
    def conf(self): ...
    @conf.setter
    def conf(self, d) -> None: ...
    def control(self): ...
    def events(self): ...
    def loader(self): ...
    def log(self): ...
    def tasks(self): ...
    @property
    def producer_pool(self): ...
    def uses_utc_timezone(self): ...
    def timezone(self): ...
App = Celery
