from _typeshed import Incomplete
from celery._state import connect_on_app_finalize as connect_on_app_finalize
from celery.utils.log import get_logger as get_logger

logger: Incomplete

def add_backend_cleanup_task(app): ...
def add_accumulate_task(app): ...
def add_unlock_chord_task(app): ...
def add_map_task(app): ...
def add_starmap_task(app): ...
def add_chunk_task(app): ...
def add_group_task(app): ...
def add_chain_task(app): ...
def add_chord_task(app): ...
