from _typeshed import Incomplete
from kombu.pidbox import Mailbox

__all__ = ['Inspect', 'Control', 'flatten_reply']

def flatten_reply(reply): ...

class Inspect:
    app: Incomplete
    destination: Incomplete
    timeout: Incomplete
    callback: Incomplete
    connection: Incomplete
    limit: Incomplete
    pattern: Incomplete
    matcher: Incomplete
    def __init__(self, destination: Incomplete | None = None, timeout: float = 1.0, callback: Incomplete | None = None, connection: Incomplete | None = None, app: Incomplete | None = None, limit: Incomplete | None = None, pattern: Incomplete | None = None, matcher: Incomplete | None = None) -> None: ...
    def report(self): ...
    def clock(self): ...
    def active(self, safe: Incomplete | None = None): ...
    def scheduled(self, safe: Incomplete | None = None): ...
    def reserved(self, safe: Incomplete | None = None): ...
    def stats(self): ...
    def revoked(self): ...
    def registered(self, *taskinfoitems): ...
    registered_tasks = registered
    def ping(self, destination: Incomplete | None = None): ...
    def active_queues(self): ...
    def query_task(self, *ids): ...
    def conf(self, with_defaults: bool = False): ...
    def hello(self, from_node, revoked: Incomplete | None = None): ...
    def memsample(self): ...
    def memdump(self, samples: int = 10): ...
    def objgraph(self, type: str = 'Request', n: int = 200, max_depth: int = 10): ...

class Control:
    Mailbox = Mailbox
    app: Incomplete
    mailbox: Incomplete
    def __init__(self, app: Incomplete | None = None) -> None: ...
    def inspect(self): ...
    def purge(self, connection: Incomplete | None = None): ...
    discard_all = purge
    def election(self, id, topic, action: Incomplete | None = None, connection: Incomplete | None = None) -> None: ...
    def revoke(self, task_id, destination: Incomplete | None = None, terminate: bool = False, signal=..., **kwargs): ...
    def revoke_by_stamped_headers(self, headers, destination: Incomplete | None = None, terminate: bool = False, signal=..., **kwargs): ...
    def terminate(self, task_id, destination: Incomplete | None = None, signal=..., **kwargs): ...
    def ping(self, destination: Incomplete | None = None, timeout: float = 1.0, **kwargs): ...
    def rate_limit(self, task_name, rate_limit, destination: Incomplete | None = None, **kwargs): ...
    def add_consumer(self, queue, exchange: Incomplete | None = None, exchange_type: str = 'direct', routing_key: Incomplete | None = None, options: Incomplete | None = None, destination: Incomplete | None = None, **kwargs): ...
    def cancel_consumer(self, queue, destination: Incomplete | None = None, **kwargs): ...
    def time_limit(self, task_name, soft: Incomplete | None = None, hard: Incomplete | None = None, destination: Incomplete | None = None, **kwargs): ...
    def enable_events(self, destination: Incomplete | None = None, **kwargs): ...
    def disable_events(self, destination: Incomplete | None = None, **kwargs): ...
    def pool_grow(self, n: int = 1, destination: Incomplete | None = None, **kwargs): ...
    def pool_shrink(self, n: int = 1, destination: Incomplete | None = None, **kwargs): ...
    def autoscale(self, max, min, destination: Incomplete | None = None, **kwargs): ...
    def shutdown(self, destination: Incomplete | None = None, **kwargs): ...
    def pool_restart(self, modules: Incomplete | None = None, reload: bool = False, reloader: Incomplete | None = None, destination: Incomplete | None = None, **kwargs): ...
    def heartbeat(self, destination: Incomplete | None = None, **kwargs): ...
    def broadcast(self, command, arguments: Incomplete | None = None, destination: Incomplete | None = None, connection: Incomplete | None = None, reply: bool = False, timeout: float = 1.0, limit: Incomplete | None = None, callback: Incomplete | None = None, channel: Incomplete | None = None, pattern: Incomplete | None = None, matcher: Incomplete | None = None, **extra_kwargs): ...
