from _typeshed import Incomplete
from collections.abc import Generator

class Events:
    receiver_cls: str
    dispatcher_cls: str
    state_cls: str
    app: Incomplete
    def __init__(self, app: Incomplete | None = None) -> None: ...
    def Receiver(self): ...
    def Dispatcher(self): ...
    def State(self): ...
    def default_dispatcher(self, hostname: Incomplete | None = None, enabled: bool = True, buffer_while_offline: bool = False) -> Generator[Incomplete]: ...
