from _typeshed import Incomplete
from celery.utils.log import ColorFormatter

__all__ = ['TaskFormatter', 'Logging']

class TaskFormatter(ColorFormatter):
    def format(self, record): ...

class Logging:
    app: Incomplete
    loglevel: Incomplete
    format: Incomplete
    task_format: Incomplete
    colorize: Incomplete
    def __init__(self, app) -> None: ...
    def setup(self, loglevel: Incomplete | None = None, logfile: Incomplete | None = None, redirect_stdouts: bool = False, redirect_level: str = 'WARNING', colorize: Incomplete | None = None, hostname: Incomplete | None = None): ...
    def redirect_stdouts(self, loglevel: Incomplete | None = None, name: str = 'celery.redirected') -> None: ...
    def setup_logging_subsystem(self, loglevel: Incomplete | None = None, logfile: Incomplete | None = None, format: Incomplete | None = None, colorize: Incomplete | None = None, hostname: Incomplete | None = None, **kwargs): ...
    def setup_task_loggers(self, loglevel: Incomplete | None = None, logfile: Incomplete | None = None, format: Incomplete | None = None, colorize: Incomplete | None = None, propagate: bool = False, **kwargs): ...
    def redirect_stdouts_to_logger(self, logger, loglevel: Incomplete | None = None, stdout: bool = True, stderr: bool = True): ...
    def supports_color(self, colorize: Incomplete | None = None, logfile: Incomplete | None = None): ...
    def colored(self, logfile: Incomplete | None = None, enabled: Incomplete | None = None): ...
    def setup_handlers(self, logger, logfile, format, colorize, formatter=..., **kwargs): ...
    def get_default_logger(self, name: str = 'celery', **kwargs): ...
