from celery.exceptions import NotRegistered

__all__ = ['TaskRegistry']

class TaskRegistry(dict):
    NotRegistered = NotRegistered
    def __missing__(self, key) -> None: ...
    def register(self, task) -> None: ...
    def unregister(self, name) -> None: ...
    def regular(self): ...
    def periodic(self): ...
    def filter_types(self, type): ...
