import re
from _typeshed import Incomplete

__all__ = ['MapRoute', 'Router', 'prepare']

Pattern = re.Pattern

class MapRoute:
    map: Incomplete
    patterns: Incomplete
    def __init__(self, map) -> None: ...
    def __call__(self, name, *args, **kwargs): ...

class Router:
    app: Incomplete
    queues: Incomplete
    routes: Incomplete
    create_missing: Incomplete
    def __init__(self, routes: Incomplete | None = None, queues: Incomplete | None = None, create_missing: bool = False, app: Incomplete | None = None) -> None: ...
    def route(self, options, name, args=(), kwargs: Incomplete | None = None, task_type: Incomplete | None = None): ...
    def expand_destination(self, route): ...
    def lookup_route(self, name, args: Incomplete | None = None, kwargs: Incomplete | None = None, options: Incomplete | None = None, task_type: Incomplete | None = None): ...
    def query_router(self, router, task, args, kwargs, options, task_type): ...

def prepare(routes): ...
