from _typeshed import Incomplete
from celery.canvas import signature
from celery.exceptions import MaxRetriesExceededError
from kombu.exceptions import OperationalError

__all__ = ['Context', 'Task']

TaskType = type

class Context:
    args: Incomplete
    callbacks: Incomplete
    called_directly: bool
    chain: Incomplete
    chord: Incomplete
    correlation_id: Incomplete
    delivery_info: Incomplete
    errbacks: Incomplete
    eta: Incomplete
    expires: Incomplete
    group: Incomplete
    group_index: Incomplete
    headers: Incomplete
    hostname: Incomplete
    id: Incomplete
    ignore_result: bool
    is_eager: bool
    kwargs: Incomplete
    logfile: Incomplete
    loglevel: Incomplete
    origin: Incomplete
    parent_id: Incomplete
    properties: Incomplete
    retries: int
    reply_to: Incomplete
    replaced_task_nesting: int
    root_id: Incomplete
    shadow: Incomplete
    taskset: Incomplete
    timelimit: Incomplete
    utc: Incomplete
    stamped_headers: Incomplete
    stamps: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def update(self, *args, **kwargs): ...
    def clear(self): ...
    def get(self, key, default: Incomplete | None = None): ...
    def as_execution_options(self): ...
    @property
    def children(self): ...

class Task:
    __trace__: Incomplete
    __v2_compat__: bool
    MaxRetriesExceededError = MaxRetriesExceededError
    OperationalError = OperationalError
    Strategy: str
    Request: str
    name: Incomplete
    typing: Incomplete
    max_retries: int
    default_retry_delay: Incomplete
    rate_limit: Incomplete
    ignore_result: Incomplete
    trail: bool
    send_events: bool
    store_errors_even_if_ignored: Incomplete
    serializer: Incomplete
    time_limit: Incomplete
    soft_time_limit: Incomplete
    backend: Incomplete
    track_started: Incomplete
    acks_late: Incomplete
    acks_on_failure_or_timeout: Incomplete
    reject_on_worker_lost: Incomplete
    throws: Incomplete
    expires: Incomplete
    priority: Incomplete
    resultrepr_maxsize: int
    request_stack: Incomplete
    abstract: bool
    __bound__: bool
    from_config: Incomplete
    @classmethod
    def bind(cls, app): ...
    @classmethod
    def on_bound(cls, app) -> None: ...
    app: Incomplete
    @classmethod
    def annotate(cls) -> None: ...
    @classmethod
    def add_around(cls, attr, around) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __reduce__(self): ...
    def run(self, *args, **kwargs) -> None: ...
    def start_strategy(self, app, consumer, **kwargs): ...
    def delay(self, *args, **kwargs): ...
    def apply_async(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, task_id: Incomplete | None = None, producer: Incomplete | None = None, link: Incomplete | None = None, link_error: Incomplete | None = None, shadow: Incomplete | None = None, **options): ...
    def shadow_name(self, args, kwargs, options) -> None: ...
    def signature_from_request(self, request: Incomplete | None = None, args: Incomplete | None = None, kwargs: Incomplete | None = None, queue: Incomplete | None = None, **extra_options): ...
    subtask_from_request = signature_from_request
    override_max_retries: Incomplete
    def retry(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, exc: Incomplete | None = None, throw: bool = True, eta: Incomplete | None = None, countdown: Incomplete | None = None, max_retries: Incomplete | None = None, **options): ...
    def apply(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, link: Incomplete | None = None, link_error: Incomplete | None = None, task_id: Incomplete | None = None, retries: Incomplete | None = None, throw: Incomplete | None = None, logfile: Incomplete | None = None, loglevel: Incomplete | None = None, headers: Incomplete | None = None, **options): ...
    def AsyncResult(self, task_id, **kwargs): ...
    def signature(self, args: Incomplete | None = None, *starargs, **starkwargs): ...
    subtask = signature
    def s(self, *args, **kwargs): ...
    def si(self, *args, **kwargs): ...
    def chunks(self, it, n): ...
    def map(self, it): ...
    def starmap(self, it): ...
    def send_event(self, type_, retry: bool = True, retry_policy: Incomplete | None = None, **fields): ...
    def replace(self, sig): ...
    def add_to_chord(self, sig, lazy: bool = False): ...
    def update_state(self, task_id: Incomplete | None = None, state: Incomplete | None = None, meta: Incomplete | None = None, **kwargs) -> None: ...
    def before_start(self, task_id, args, kwargs) -> None: ...
    def on_success(self, retval, task_id, args, kwargs) -> None: ...
    def on_retry(self, exc, task_id, args, kwargs, einfo) -> None: ...
    def on_failure(self, exc, task_id, args, kwargs, einfo) -> None: ...
    def after_return(self, status, retval, task_id, args, kwargs, einfo) -> None: ...
    def on_replace(self, sig): ...
    def add_trail(self, result): ...
    def push_request(self, *args, **kwargs) -> None: ...
    def pop_request(self) -> None: ...
    request: Incomplete
    @property
    def backend(self): ...
    @backend.setter
    def backend(self, value) -> None: ...
BaseTask = Task
