from _typeshed import Incomplete
from typing import NamedTuple

__all__ = ['TraceInfo', 'build_tracer', 'trace_task', 'setup_worker_optimizations', 'reset_worker_optimizations']

class log_policy_t(NamedTuple):
    format: Incomplete
    description: Incomplete
    severity: Incomplete
    traceback: Incomplete
    mail: Incomplete

class trace_ok_t(NamedTuple):
    retval: Incomplete
    info: Incomplete
    runtime: Incomplete
    retstr: Incomplete

class TraceInfo:
    state: Incomplete
    retval: Incomplete
    def __init__(self, state, retval: Incomplete | None = None) -> None: ...
    def handle_error_state(self, task, req, eager: bool = False, call_errbacks: bool = True): ...
    def handle_reject(self, task, req, **kwargs) -> None: ...
    def handle_ignore(self, task, req, **kwargs) -> None: ...
    def handle_retry(self, task, req, store_errors: bool = True, **kwargs): ...
    def handle_failure(self, task, req, store_errors: bool = True, call_errbacks: bool = True): ...

def build_tracer(name, task, loader: Incomplete | None = None, hostname: Incomplete | None = None, store_errors: bool = True, Info=..., eager: bool = False, propagate: bool = False, app: Incomplete | None = None, monotonic=..., trace_ok_t=..., IGNORE_STATES=...): ...
def trace_task(task, uuid, args, kwargs, request: Incomplete | None = None, **opts): ...
def setup_worker_optimizations(app, hostname: Incomplete | None = None) -> None: ...
def reset_worker_optimizations(app=...) -> None: ...
