from _typeshed import Incomplete
from billiard import pool as _pool
from typing import NamedTuple

__all__ = ['AsynPool']

class Ack(NamedTuple):
    id: Incomplete
    fd: Incomplete
    payload: Incomplete

class Worker(_pool.Worker):
    def on_loop_start(self, pid) -> None: ...

class ResultHandler(_pool.ResultHandler):
    fileno_to_outq: Incomplete
    on_process_alive: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def register_with_event_loop(self, hub) -> None: ...
    def handle_event(self, *args) -> None: ...
    def on_stop_not_started(self) -> None: ...

class AsynPool(_pool.Pool):
    ResultHandler = ResultHandler
    Worker = Worker
    def WorkerProcess(self, worker): ...
    sched_strategy: Incomplete
    synack: Incomplete
    outbound_buffer: Incomplete
    write_stats: Incomplete
    on_soft_timeout: Incomplete
    on_hard_timeout: Incomplete
    def __init__(self, processes: Incomplete | None = None, synack: bool = False, sched_strategy: Incomplete | None = None, proc_alive_timeout: Incomplete | None = None, *args, **kwargs) -> None: ...
    handle_result_event: Incomplete
    def register_with_event_loop(self, hub) -> None: ...
    def on_job_ready(self, job, i, obj, inqW_fd) -> None: ...
    def flush(self) -> None: ...
    def get_process_queues(self): ...
    def on_grow(self, n) -> None: ...
    def on_shrink(self, n) -> None: ...
    def create_process_queues(self): ...
    def on_process_alive(self, pid): ...
    def on_job_process_down(self, job, pid_gone) -> None: ...
    def on_job_process_lost(self, job, pid, exitcode) -> None: ...
    def human_write_stats(self): ...
    def create_result_handler(self): ...
    def process_flush_queues(self, proc) -> None: ...
    def on_partial_read(self, job, proc) -> None: ...
    def destroy_queues(self, queues, proc): ...
    @property
    def timers(self): ...
