from . import base
from _typeshed import Incomplete
from kombu.asynchronous import timer as _timer

__all__ = ['TaskPool']

class Timer(_timer.Timer):
    GreenletExit: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def clear(self) -> None: ...
    def cancel(self, tref) -> None: ...
    @property
    def queue(self): ...

class TaskPool(base.BasePool):
    Timer = Timer
    signal_safe: bool
    is_green: bool
    task_join_will_block: bool
    Pool: Incomplete
    getcurrent: Incomplete
    getpid: Incomplete
    spawn_n: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def on_start(self) -> None: ...
    def on_stop(self) -> None: ...
    def on_apply(self, target, args: Incomplete | None = None, kwargs: Incomplete | None = None, callback: Incomplete | None = None, accept_callback: Incomplete | None = None, **_) -> None: ...
    limit: Incomplete
    def grow(self, n: int = 1) -> None: ...
    def shrink(self, n: int = 1) -> None: ...
    def terminate_job(self, pid, signal: Incomplete | None = None) -> None: ...
