from . import base
from _typeshed import Incomplete
from kombu.asynchronous import timer as _timer

__all__ = ['TaskPool']

class Timer(_timer.Timer):
    def __init__(self, *args, **kwargs) -> None: ...
    def clear(self) -> None: ...
    @property
    def queue(self): ...

class TaskPool(base.BasePool):
    Timer = Timer
    signal_safe: bool
    is_green: bool
    task_join_will_block: bool
    Pool: Incomplete
    spawn_n: Incomplete
    timeout: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def on_start(self) -> None: ...
    def on_stop(self) -> None: ...
    def on_apply(self, target, args: Incomplete | None = None, kwargs: Incomplete | None = None, callback: Incomplete | None = None, accept_callback: Incomplete | None = None, timeout: Incomplete | None = None, timeout_callback: Incomplete | None = None, apply_target=..., **_): ...
    def grow(self, n: int = 1) -> None: ...
    def shrink(self, n: int = 1) -> None: ...
    @property
    def num_processes(self): ...
