from .asynpool import AsynPool
from _typeshed import Incomplete
from billiard.pool import Pool as BlockingPool
from celery.concurrency.base import BasePool

__all__ = ['TaskPool', 'process_initializer', 'process_destructor']

def process_initializer(app, hostname) -> None: ...
def process_destructor(pid, exitcode) -> None: ...

class TaskPool(BasePool):
    Pool = AsynPool
    BlockingPool = BlockingPool
    uses_semaphore: bool
    write_stats: Incomplete
    on_apply: Incomplete
    maintain_pool: Incomplete
    terminate_job: Incomplete
    grow: Incomplete
    shrink: Incomplete
    flush: Incomplete
    def on_start(self) -> None: ...
    def restart(self) -> None: ...
    def did_start_ok(self): ...
    def register_with_event_loop(self, loop): ...
    def on_stop(self) -> None: ...
    def on_terminate(self) -> None: ...
    def on_close(self) -> None: ...
    @property
    def num_processes(self): ...
