# Generated by Django 4.2.19 on 2025-03-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessingJobProxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Job",
                "verbose_name_plural": "Processing Jobs",
            },
        ),
        migrations.CreateModel(
            name="ReceiptTemplateProxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receipt Template",
                "verbose_name_plural": "Receipt Templates",
            },
        ),
    ]
