from celery import bootsteps

__all__ = ['Connection']

class Connection(bootsteps.StartStopStep):
    def __init__(self, c, **kwargs) -> None: ...
    def start(self, c) -> None: ...
    def shutdown(self, c) -> None: ...
    def info(self, c): ...
