from _typeshed import Incomplete
from celery import bootsteps

__all__ = ['Gossip']

class Gossip(bootsteps.ConsumerStep):
    label: str
    requires: Incomplete
    compatible_transports: Incomplete
    enabled: Incomplete
    app: Incomplete
    Receiver: Incomplete
    hostname: Incomplete
    full_hostname: Incomplete
    on: Incomplete
    timer: Incomplete
    state: Incomplete
    update_state: Incomplete
    interval: Incomplete
    heartbeat_interval: Incomplete
    consensus_requests: Incomplete
    consensus_replies: Incomplete
    event_handlers: Incomplete
    clock: Incomplete
    election_handlers: Incomplete
    def __init__(self, c, without_gossip: bool = False, interval: float = 5.0, heartbeat_interval: float = 2.0, **kwargs) -> None: ...
    def compatible_transport(self, app): ...
    def election(self, id, topic, action: Incomplete | None = None) -> None: ...
    def call_task(self, task) -> None: ...
    def on_elect(self, event): ...
    dispatcher: Incomplete
    def start(self, c) -> None: ...
    def on_elect_ack(self, event) -> None: ...
    def on_node_join(self, worker) -> None: ...
    def on_node_leave(self, worker) -> None: ...
    def on_node_lost(self, worker) -> None: ...
    def register_timer(self) -> None: ...
    def periodic(self) -> None: ...
    def get_consumers(self, channel): ...
    def on_message(self, prepare, message): ...
