from _typeshed import Incomplete
from celery import bootsteps

__all__ = ['Mingle']

class Mingle(bootsteps.StartStopStep):
    label: str
    requires: Incomplete
    compatible_transports: Incomplete
    enabled: Incomplete
    def __init__(self, c, without_mingle: bool = False, **kwargs) -> None: ...
    def compatible_transport(self, app): ...
    def start(self, c) -> None: ...
    def sync(self, c) -> None: ...
    def send_hello(self, c): ...
    def on_node_reply(self, c, nodename, reply) -> None: ...
    def sync_with_node(self, c, clock: Incomplete | None = None, revoked: Incomplete | None = None, **kwargs) -> None: ...
    def on_clock_event(self, c, clock) -> None: ...
    def on_revoked_received(self, c, revoked) -> None: ...
