from _typeshed import Incomplete
from celery import bootsteps

__all__ = ['Tasks']

class Tasks(bootsteps.StartStopStep):
    requires: Incomplete
    def __init__(self, c, **kwargs) -> None: ...
    def start(self, c): ...
    def stop(self, c) -> None: ...
    def shutdown(self, c) -> None: ...
    def info(self, c): ...
