"""
Django settings for parser project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import mongoengine
from celery.schedules import crontab
from pathlib import Path
import django_stubs_ext
from urllib import parse
import os
from datetime import timedelta
from os import path
import sys

django_stubs_ext.monkeypatch()

BASE_DIR = Path(__file__).resolve().parent.parent

MONGODB_SOCKET = parse.quote_plus(
    path.join('../', 'general', 'server', 'db',  'general.sock'))

sys.path.append(str(BASE_DIR.parent))

sys.path.append(str(BASE_DIR))

print(sys.path)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Temp upload directory for job processing (not web accessible)
TEMP_UPLOAD_DIR = os.path.join(BASE_DIR, 'server', 'tmp_uploads')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oyajap)nc^ur#$v)67oj4p86=2sezj$5pwx$!f%e2gmu=xxjqr'

# This must match the general server's SECRET_KEY for JWT verification to work

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Minimal set of apps for a lightweight parser service
    'django.contrib.sessions',          # Required by rest_framework_simplejwt
    'django.contrib.contenttypes',  # Keep this as some core functionality depends on it
    'django.contrib.auth',          # Required by rest_framework_simplejwt
    'apps.jobs',
    'apps.optics',
    'rest_framework',
    'rest_framework_simplejwt'
]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    # Removed CSRF middleware as it's not needed for API-only service
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Required for JWT auth
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'apps.jobs.views.APIKeyAuthentication',  # API key authentication middleware
]

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_WORKER_CONCURRENCY = 3  # Limit to 3 concurrent jobs
CELERY_TASK_ACKS_LATE = True  # Ensure tasks aren't lost on worker crash

# Celery Beat Schedule

CELERY_BEAT_SCHEDULE = {
    'template-maintenance-daily': {
        'task': 'apps.optics.tasks.run_template_maintenance',
        'schedule': crontab(hour='3', minute='0'),  # Run at 3:00 AM every day
        'options': {'expires': 60 * 60 * 24},  # Expire after 24 hours
    },
    'temp-file-cleanup-daily': {
        'task': 'apps.jobs.tasks.cleanup_temporary_files',
        'schedule': crontab(hour='2', minute='0'),  # Run at 2:00 AM every day
        'options': {'expires': 60 * 60 * 24},  # Expire after 24 hours
    },
    'old-job-cleanup-weekly': {
        'task': 'apps.jobs.tasks.cleanup_old_jobs',
        # Run at 1:00 AM every Monday
        'schedule': crontab(hour='1', minute='0', day_of_week='1'),
        'options': {'expires': 60 * 60 * 24},  # Expire after 24 hours
    },
}

ROOT_URLCONF = 'parser.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'parser.wsgi.application'

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


# Connect to MongoDB
mongoengine.connect(
    db='receipt_scanner_db',
    host='mongodb://'+MONGODB_SOCKET
)

# Django still needs a database for its own functionality
# This will be unused but is required for Django to work
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation - not needed for lightweight parser service
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# API Authentication Key
API_KEY = 'test_api_key'
