from _typeshed import Incomplete
from celery import bootsteps
from celery.utils.threads import bgThread

__all__ = ['Autoscaler', 'WorkerComponent']

class WorkerComponent(bootsteps.StartStopStep):
    label: str
    conditional: bool
    requires: Incomplete
    enabled: Incomplete
    def __init__(self, w, **kwargs) -> None: ...
    def create(self, w): ...
    def register_with_event_loop(self, w, hub) -> None: ...
    def info(self, w): ...

class Autoscaler(bgThread):
    pool: Incomplete
    mutex: Incomplete
    max_concurrency: Incomplete
    min_concurrency: Incomplete
    keepalive: Incomplete
    worker: Incomplete
    def __init__(self, pool, max_concurrency, min_concurrency: int = 0, worker: Incomplete | None = None, keepalive=..., mutex: Incomplete | None = None) -> None: ...
    def body(self) -> None: ...
    def maybe_scale(self, req: Incomplete | None = None) -> None: ...
    def update(self, max: Incomplete | None = None, min: Incomplete | None = None): ...
    def scale_up(self, n): ...
    def scale_down(self, n): ...
    def info(self): ...
    @property
    def qty(self): ...
    @property
    def processes(self): ...
