from _typeshed import Incomplete
from celery import bootsteps

__all__ = ['Timer', 'Hub', 'Pool', 'Beat', 'StateDB', 'Consumer']

class Timer(bootsteps.Step):
    def create(self, w) -> None: ...
    def on_timer_error(self, exc) -> None: ...
    def on_timer_tick(self, delay) -> None: ...

class Hub(bootsteps.StartStopStep):
    requires: Incomplete
    def __init__(self, w, **kwargs) -> None: ...
    def include_if(self, w): ...
    def create(self, w): ...
    def start(self, w) -> None: ...
    def stop(self, w) -> None: ...
    def terminate(self, w) -> None: ...

class Pool(bootsteps.StartStopStep):
    requires: Incomplete
    optimization: Incomplete
    def __init__(self, w, autoscale: Incomplete | None = None, **kwargs) -> None: ...
    def close(self, w) -> None: ...
    def terminate(self, w) -> None: ...
    def create(self, w): ...
    def info(self, w): ...
    def register_with_event_loop(self, w, hub) -> None: ...

class Beat(bootsteps.StartStopStep):
    label: str
    conditional: bool
    enabled: Incomplete
    def __init__(self, w, beat: bool = False, **kwargs) -> None: ...
    def create(self, w): ...

class StateDB(bootsteps.Step):
    enabled: Incomplete
    def __init__(self, w, **kwargs) -> None: ...
    def create(self, w) -> None: ...

class Consumer(bootsteps.StartStopStep):
    last: bool
    def create(self, w): ...
