__all__ = ['asynloop', 'synloop']

def asynloop(obj, connection, consumer, blueprint, hub, qos, heartbeat, clock, hbrate: float = 2.0) -> None: ...
def synloop(obj, connection, consumer, blueprint, hub, qos, heartbeat, clock, hbrate: float = 2.0, **kwargs) -> None: ...
