from _typeshed import Incomplete

__all__ = ['Pidbox', 'gPidbox']

class Pidbox:
    consumer: Incomplete
    c: Incomplete
    hostname: Incomplete
    node: Incomplete
    def __init__(self, c) -> None: ...
    def on_message(self, body, message) -> None: ...
    def start(self, c) -> None: ...
    def on_stop(self) -> None: ...
    def stop(self, c) -> None: ...
    def reset(self) -> None: ...
    def shutdown(self, c) -> None: ...

class gPidbox(Pidbox):
    def start(self, c) -> None: ...
    def on_stop(self) -> None: ...
    def reset(self) -> None: ...
    def loop(self, c) -> None: ...
