from . import state
from _typeshed import Incomplete
from celery.concurrency.base import BasePool

__all__ = ['Request']

task_accepted = state.task_accepted
task_ready = state.task_ready

class Request:
    acknowledged: bool
    time_start: Incomplete
    worker_pid: Incomplete
    time_limits: Incomplete
    id: Incomplete
    name: Incomplete
    def __init__(self, message, on_ack=..., hostname: Incomplete | None = None, eventer: Incomplete | None = None, app: Incomplete | None = None, connection_errors: Incomplete | None = None, request_dict: Incomplete | None = None, task: Incomplete | None = None, on_reject=..., body: Incomplete | None = None, headers: Incomplete | None = None, decoded: bool = False, utc: bool = True, maybe_make_aware=..., maybe_iso8601=..., **opts) -> None: ...
    @property
    def delivery_info(self): ...
    @property
    def message(self): ...
    @property
    def request_dict(self): ...
    @property
    def body(self): ...
    @property
    def app(self): ...
    @property
    def utc(self): ...
    @property
    def content_type(self): ...
    @property
    def content_encoding(self): ...
    @property
    def type(self): ...
    @property
    def root_id(self): ...
    @property
    def parent_id(self): ...
    @property
    def argsrepr(self): ...
    @property
    def args(self): ...
    @property
    def kwargs(self): ...
    @property
    def kwargsrepr(self): ...
    @property
    def on_ack(self): ...
    @property
    def on_reject(self): ...
    @on_reject.setter
    def on_reject(self, value) -> None: ...
    @property
    def hostname(self): ...
    @property
    def ignore_result(self): ...
    @property
    def eventer(self): ...
    @eventer.setter
    def eventer(self, eventer) -> None: ...
    @property
    def connection_errors(self): ...
    @property
    def task(self): ...
    @property
    def eta(self): ...
    @property
    def expires(self): ...
    @expires.setter
    def expires(self, value) -> None: ...
    @property
    def tzlocal(self): ...
    @property
    def store_errors(self): ...
    @property
    def task_id(self): ...
    @task_id.setter
    def task_id(self, value) -> None: ...
    @property
    def task_name(self): ...
    @task_name.setter
    def task_name(self, value) -> None: ...
    @property
    def reply_to(self): ...
    @property
    def replaced_task_nesting(self): ...
    @property
    def groups(self): ...
    @property
    def stamped_headers(self) -> list: ...
    @property
    def stamps(self) -> dict: ...
    @property
    def correlation_id(self): ...
    def execute_using_pool(self, pool: BasePool, **kwargs): ...
    def execute(self, loglevel: Incomplete | None = None, logfile: Incomplete | None = None): ...
    def maybe_expire(self): ...
    def terminate(self, pool, signal: Incomplete | None = None) -> None: ...
    def cancel(self, pool, signal: Incomplete | None = None) -> None: ...
    def revoked(self): ...
    def send_event(self, type, **fields) -> None: ...
    def on_accepted(self, pid, time_accepted) -> None: ...
    def on_timeout(self, soft, timeout) -> None: ...
    def on_success(self, failed__retval__runtime, **kwargs): ...
    def on_retry(self, exc_info) -> None: ...
    def on_failure(self, exc_info, send_failed_event: bool = True, return_ok: bool = False): ...
    def acknowledge(self) -> None: ...
    def reject(self, requeue: bool = False) -> None: ...
    def info(self, safe: bool = False): ...
    def humaninfo(self): ...
    def chord(self): ...
    def errbacks(self): ...
    def group(self): ...
    def group_index(self): ...
