import shelve
import zlib
from _typeshed import Incomplete
from kombu.serialization import pickle_protocol

__all__ = ['SOFTWARE_INFO', 'reserved_requests', 'active_requests', 'total_count', 'revoked', 'task_reserved', 'maybe_shutdown', 'task_accepted', 'task_ready', 'Persistent']

SOFTWARE_INFO: Incomplete
reserved_requests: Incomplete
active_requests: Incomplete
total_count: Incomplete
revoked: Incomplete

def maybe_shutdown() -> None: ...
def task_reserved(request, add_request=..., add_reserved_request=...) -> None: ...
def task_accepted(request, _all_total_count: Incomplete | None = None, add_request=..., add_active_request=..., add_to_total_count=...) -> None: ...
def task_ready(request, successful: bool = False, remove_request=..., discard_active_request=..., discard_reserved_request=...) -> None: ...
bench_every = C_BENCH_EVERY

class Persistent:
    storage = shelve
    protocol = pickle_protocol
    compress = zlib.compress
    decompress = zlib.decompress
    state: Incomplete
    filename: Incomplete
    clock: Incomplete
    def __init__(self, state, filename, clock: Incomplete | None = None) -> None: ...
    def open(self): ...
    def merge(self) -> None: ...
    def sync(self) -> None: ...
    def close(self) -> None: ...
    def save(self) -> None: ...
    def db(self): ...
