from _typeshed import Incomplete
from celery import bootsteps

__all__ = ['WorkController']

class WorkController:
    app: Incomplete
    pidlock: Incomplete
    blueprint: Incomplete
    pool: Incomplete
    semaphore: Incomplete
    exitcode: Incomplete
    class Blueprint(bootsteps.Blueprint):
        name: str
        default_steps: Incomplete
    hostname: Incomplete
    startup_time: Incomplete
    def __init__(self, app: Incomplete | None = None, hostname: Incomplete | None = None, **kwargs) -> None: ...
    pidfile: Incomplete
    concurrency: Incomplete
    loglevel: Incomplete
    ready_callback: Incomplete
    use_eventloop: Incomplete
    options: Incomplete
    pool_cls: Incomplete
    steps: Incomplete
    def setup_instance(self, queues: Incomplete | None = None, ready_callback: Incomplete | None = None, pidfile: Incomplete | None = None, include: Incomplete | None = None, use_eventloop: Incomplete | None = None, exclude_queues: Incomplete | None = None, **kwargs) -> None: ...
    def on_init_blueprint(self) -> None: ...
    def on_before_init(self, **kwargs) -> None: ...
    def on_after_init(self, **kwargs) -> None: ...
    def on_start(self) -> None: ...
    def on_consumer_ready(self, consumer) -> None: ...
    def on_close(self) -> None: ...
    def on_stopped(self) -> None: ...
    def setup_queues(self, include, exclude: Incomplete | None = None) -> None: ...
    include: Incomplete
    def setup_includes(self, includes) -> None: ...
    def prepare_args(self, **kwargs): ...
    def start(self) -> None: ...
    def register_with_event_loop(self, hub) -> None: ...
    def signal_consumer_close(self) -> None: ...
    def should_use_eventloop(self): ...
    def stop(self, in_sighandler: bool = False, exitcode: Incomplete | None = None) -> None: ...
    def terminate(self, in_sighandler: bool = False) -> None: ...
    def reload(self, modules: Incomplete | None = None, reload: bool = False, reloader: Incomplete | None = None) -> None: ...
    def info(self): ...
    def rusage(self): ...
    def stats(self): ...
    @property
    def state(self): ...
    logfile: Incomplete
    task_events: Incomplete
    consumer_cls: Incomplete
    timer_cls: Incomplete
    timer_precision: Incomplete
    optimization: Incomplete
    autoscaler_cls: Incomplete
    pool_putlocks: Incomplete
    pool_restarts: Incomplete
    statedb: Incomplete
    schedule_filename: Incomplete
    scheduler: Incomplete
    time_limit: Incomplete
    soft_time_limit: Incomplete
    max_tasks_per_child: Incomplete
    max_memory_per_child: Incomplete
    prefetch_multiplier: Incomplete
    disable_rate_limits: Incomplete
    worker_lost_wait: Incomplete
    def setup_defaults(self, concurrency: Incomplete | None = None, loglevel: str = 'WARN', logfile: Incomplete | None = None, task_events: Incomplete | None = None, pool: Incomplete | None = None, consumer_cls: Incomplete | None = None, timer_cls: Incomplete | None = None, timer_precision: Incomplete | None = None, autoscaler_cls: Incomplete | None = None, pool_putlocks: Incomplete | None = None, pool_restarts: Incomplete | None = None, optimization: Incomplete | None = None, O: Incomplete | None = None, statedb: Incomplete | None = None, time_limit: Incomplete | None = None, soft_time_limit: Incomplete | None = None, scheduler: Incomplete | None = None, pool_cls: Incomplete | None = None, state_db: Incomplete | None = None, task_time_limit: Incomplete | None = None, task_soft_time_limit: Incomplete | None = None, scheduler_cls: Incomplete | None = None, schedule_filename: Incomplete | None = None, max_tasks_per_child: Incomplete | None = None, prefetch_multiplier: Incomplete | None = None, disable_rate_limits: Incomplete | None = None, worker_lost_wait: Incomplete | None = None, max_memory_per_child: Incomplete | None = None, **_kw) -> None: ...
