import shelve
from _typeshed import Incomplete
from billiard.context import Process
from threading import Thread
from typing import NamedTuple

__all__ = ['SchedulingError', 'ScheduleEntry', 'Scheduler', 'PersistentScheduler', 'Service', 'EmbeddedService']

class event_t(NamedTuple):
    time: Incomplete
    priority: Incomplete
    entry: Incomplete

class SchedulingError(Exception): ...

class BeatLazyFunc:
    def __init__(self, func, *args, **kwargs) -> None: ...
    def __call__(self): ...
    def delay(self): ...

class ScheduleEntry:
    name: Incomplete
    schedule: Incomplete
    args: Incomplete
    kwargs: Incomplete
    options: Incomplete
    last_run_at: Incomplete
    total_run_count: int
    app: Incomplete
    task: Incomplete
    def __init__(self, name: Incomplete | None = None, task: Incomplete | None = None, last_run_at: Incomplete | None = None, total_run_count: Incomplete | None = None, schedule: Incomplete | None = None, args=(), kwargs: Incomplete | None = None, options: Incomplete | None = None, relative: bool = False, app: Incomplete | None = None) -> None: ...
    def default_now(self): ...
    __next__: Incomplete
    next: Incomplete
    def __reduce__(self): ...
    def update(self, other) -> None: ...
    def is_due(self): ...
    def __iter__(self): ...
    def __lt__(self, other): ...
    def editable_fields_equal(self, other): ...
    def __eq__(self, other): ...

class Scheduler:
    Entry = ScheduleEntry
    schedule: Incomplete
    max_interval = DEFAULT_MAX_INTERVAL
    sync_every: Incomplete
    sync_every_tasks: Incomplete
    logger = logger
    app: Incomplete
    data: Incomplete
    Producer: Incomplete
    old_schedulers: Incomplete
    def __init__(self, app, schedule: Incomplete | None = None, max_interval: Incomplete | None = None, Producer: Incomplete | None = None, lazy: bool = False, sync_every_tasks: Incomplete | None = None, **kwargs) -> None: ...
    def install_default_entries(self, data) -> None: ...
    def apply_entry(self, entry, producer: Incomplete | None = None) -> None: ...
    def adjust(self, n, drift: float = -0.01): ...
    def is_due(self, entry): ...
    def populate_heap(self, event_t=..., heapify=...) -> None: ...
    def tick(self, event_t=..., min=..., heappop=..., heappush=...): ...
    def schedules_equal(self, old_schedules, new_schedules): ...
    def should_sync(self): ...
    def reserve(self, entry): ...
    def apply_async(self, entry, producer: Incomplete | None = None, advance: bool = True, **kwargs): ...
    def send_task(self, *args, **kwargs): ...
    def setup_schedule(self) -> None: ...
    def sync(self) -> None: ...
    def close(self) -> None: ...
    def add(self, **kwargs): ...
    def update_from_dict(self, dict_) -> None: ...
    def merge_inplace(self, b) -> None: ...
    def get_schedule(self): ...
    def set_schedule(self, schedule) -> None: ...
    def connection(self): ...
    def producer(self): ...
    @property
    def info(self): ...

class PersistentScheduler(Scheduler):
    persistence = shelve
    known_suffixes: Incomplete
    schedule_filename: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def setup_schedule(self) -> None: ...
    def get_schedule(self): ...
    def set_schedule(self, schedule) -> None: ...
    schedule: Incomplete
    def sync(self) -> None: ...
    def close(self) -> None: ...
    @property
    def info(self): ...

class Service:
    scheduler_cls = PersistentScheduler
    app: Incomplete
    max_interval: Incomplete
    schedule_filename: Incomplete
    def __init__(self, app, max_interval: Incomplete | None = None, schedule_filename: Incomplete | None = None, scheduler_cls: Incomplete | None = None) -> None: ...
    def __reduce__(self): ...
    def start(self, embedded_process: bool = False) -> None: ...
    def sync(self) -> None: ...
    def stop(self, wait: bool = False) -> None: ...
    def get_scheduler(self, lazy: bool = False, extension_namespace: str = 'celery.beat_schedulers'): ...
    def scheduler(self): ...

class _Threaded(Thread):
    app: Incomplete
    service: Incomplete
    daemon: bool
    name: str
    def __init__(self, app, **kwargs) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...

class _Process(Process):
    app: Incomplete
    service: Incomplete
    name: str
    def __init__(self, app, **kwargs) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...

def EmbeddedService(app, max_interval: Incomplete | None = None, **kwargs): ...
