from .utils.graph import GraphFormatter
from _typeshed import Incomplete

__all__ = ['Blueprint', 'Step', 'StartStopStep', 'ConsumerStep']

class StepFormatter(GraphFormatter):
    blueprint_prefix: str
    conditional_prefix: str
    blueprint_scheme: Incomplete
    def label(self, step): ...
    def node(self, obj, **attrs): ...
    def edge(self, a, b, **attrs): ...

class Blueprint:
    GraphFormatter = StepFormatter
    name: Incomplete
    state: Incomplete
    started: int
    default_steps: Incomplete
    state_to_name: Incomplete
    types: Incomplete
    on_start: Incomplete
    on_close: Incomplete
    on_stopped: Incomplete
    shutdown_complete: Incomplete
    steps: Incomplete
    def __init__(self, steps: Incomplete | None = None, name: Incomplete | None = None, on_start: Incomplete | None = None, on_close: Incomplete | None = None, on_stopped: Incomplete | None = None) -> None: ...
    def start(self, parent) -> None: ...
    def human_state(self): ...
    def info(self, parent): ...
    def close(self, parent) -> None: ...
    def restart(self, parent, method: str = 'stop', description: str = 'restarting', propagate: bool = False) -> None: ...
    def send_all(self, parent, method, description: Incomplete | None = None, reverse: bool = True, propagate: bool = True, args=()) -> None: ...
    def stop(self, parent, close: bool = True, terminate: bool = False) -> None: ...
    def join(self, timeout: Incomplete | None = None) -> None: ...
    def apply(self, parent, **kwargs): ...
    def connect_with(self, other) -> None: ...
    def __getitem__(self, name): ...
    def claim_steps(self): ...
    def load_step(self, step): ...
    @property
    def alias(self): ...

class StepType(type):
    name: Incomplete
    requires: Incomplete
    def __new__(cls, name, bases, attrs): ...

class Step(metaclass=StepType):
    name: Incomplete
    label: Incomplete
    conditional: bool
    requires: Incomplete
    last: bool
    enabled: bool
    def __init__(self, parent, **kwargs) -> None: ...
    def include_if(self, parent): ...
    def instantiate(self, name, *args, **kwargs): ...
    def include(self, parent): ...
    def create(self, parent) -> None: ...
    @property
    def alias(self): ...
    def info(self, obj) -> None: ...

class StartStopStep(Step):
    obj: Incomplete
    def start(self, parent): ...
    def stop(self, parent): ...
    def close(self, parent) -> None: ...
    def terminate(self, parent): ...
    def include(self, parent): ...

class ConsumerStep(StartStopStep):
    requires: Incomplete
    consumers: Incomplete
    def get_consumers(self, channel) -> None: ...
    def start(self, c) -> None: ...
    def stop(self, c) -> None: ...
    def shutdown(self, c) -> None: ...
