from _typeshed import Incomplete
from abc import ABCMeta, abstractmethod
from collections.abc import Generator

__all__ = ['Signature', 'chain', 'xmap', 'xstarmap', 'chunks', 'group', 'chord', 'signature', 'maybe_signature']

class StampingVisitor(metaclass=ABCMeta):
    def on_group_start(self, group, **headers) -> dict: ...
    def on_group_end(self, group, **headers) -> None: ...
    def on_chain_start(self, chain, **headers) -> dict: ...
    def on_chain_end(self, chain, **headers) -> None: ...
    @abstractmethod
    def on_signature(self, sig, **headers) -> dict: ...
    def on_chord_header_start(self, sig, **header) -> dict: ...
    def on_chord_header_end(self, sig, **header) -> None: ...
    def on_chord_body(self, sig, **header) -> dict: ...
    def on_callback(self, callback, **header) -> dict: ...
    def on_errback(self, errback, **header) -> dict: ...

class Signature(dict):
    TYPES: Incomplete
    @classmethod
    def register_type(cls, name: Incomplete | None = None): ...
    @classmethod
    def from_dict(cls, d, app: Incomplete | None = None): ...
    def __init__(self, task: Incomplete | None = None, args: Incomplete | None = None, kwargs: Incomplete | None = None, options: Incomplete | None = None, type: Incomplete | None = None, subtask_type: Incomplete | None = None, immutable: bool = False, app: Incomplete | None = None, **ex) -> None: ...
    def __call__(self, *partial_args, **partial_kwargs): ...
    def delay(self, *partial_args, **partial_kwargs): ...
    def apply(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, **options): ...
    def apply_async(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, route_name: Incomplete | None = None, **options): ...
    def clone(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, **opts): ...
    partial = clone
    def freeze(self, _id: Incomplete | None = None, group_id: Incomplete | None = None, chord: Incomplete | None = None, root_id: Incomplete | None = None, parent_id: Incomplete | None = None, group_index: Incomplete | None = None): ...
    def replace(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, options: Incomplete | None = None): ...
    def set(self, immutable: Incomplete | None = None, **options): ...
    immutable: Incomplete
    def set_immutable(self, immutable) -> None: ...
    def stamp(self, visitor: Incomplete | None = None, append_stamps: bool = False, **headers): ...
    def stamp_links(self, visitor, append_stamps: bool = False, **headers) -> None: ...
    def append_to_list_option(self, key, value): ...
    def extend_list_option(self, key, value) -> None: ...
    def link(self, callback): ...
    def link_error(self, errback): ...
    def on_error(self, errback): ...
    def flatten_links(self): ...
    def __or__(self, other): ...
    def __ior__(self, other): ...
    def election(self): ...
    def reprcall(self, *args, **kwargs): ...
    def __deepcopy__(self, memo): ...
    def __invert__(self): ...
    def __reduce__(self): ...
    def __json__(self): ...
    def items(self) -> Generator[Incomplete]: ...
    @property
    def name(self): ...
    def type(self): ...
    def app(self): ...
    def AsyncResult(self): ...
    id: Incomplete
    parent_id: Incomplete
    root_id: Incomplete
    task: Incomplete
    args: Incomplete
    kwargs: Incomplete
    options: Incomplete
    subtask_type: Incomplete

class _chain(Signature):
    tasks: Incomplete
    @classmethod
    def from_dict(cls, d, app: Incomplete | None = None): ...
    subtask_type: str
    def __init__(self, *tasks, **options) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __or__(self, other): ...
    def clone(self, *args, **kwargs): ...
    def unchain_tasks(self): ...
    def apply_async(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, **options): ...
    def run(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, group_id: Incomplete | None = None, chord: Incomplete | None = None, task_id: Incomplete | None = None, link: Incomplete | None = None, link_error: Incomplete | None = None, publisher: Incomplete | None = None, producer: Incomplete | None = None, root_id: Incomplete | None = None, parent_id: Incomplete | None = None, app: Incomplete | None = None, group_index: Incomplete | None = None, **options): ...
    def freeze(self, _id: Incomplete | None = None, group_id: Incomplete | None = None, chord: Incomplete | None = None, root_id: Incomplete | None = None, parent_id: Incomplete | None = None, group_index: Incomplete | None = None): ...
    def stamp(self, visitor: Incomplete | None = None, append_stamps: bool = False, **headers) -> None: ...
    id: Incomplete
    def prepare_steps(self, args, kwargs, tasks, root_id: Incomplete | None = None, parent_id: Incomplete | None = None, link_error: Incomplete | None = None, app: Incomplete | None = None, last_task_id: Incomplete | None = None, group_id: Incomplete | None = None, chord_body: Incomplete | None = None, clone: bool = True, from_dict=..., group_index: Incomplete | None = None): ...
    def apply(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, **options): ...
    @property
    def app(self): ...

class chain(_chain):
    def __new__(cls, *tasks, **kwargs): ...

class _basemap(Signature):
    @classmethod
    def from_dict(cls, d, app: Incomplete | None = None): ...
    def __init__(self, task, it, **options) -> None: ...
    def apply_async(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, **opts): ...

class xmap(_basemap): ...
class xstarmap(_basemap): ...

class chunks(Signature):
    @classmethod
    def from_dict(cls, d, app: Incomplete | None = None): ...
    def __init__(self, task, it, n, **options) -> None: ...
    def __call__(self, **options): ...
    def apply_async(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, **opts): ...
    def group(self): ...
    @classmethod
    def apply_chunks(cls, task, it, n, app: Incomplete | None = None): ...

class group(Signature):
    tasks: Incomplete
    @classmethod
    def from_dict(cls, d, app: Incomplete | None = None): ...
    subtask_type: str
    def __init__(self, *tasks, **options) -> None: ...
    def __call__(self, *partial_args, **options): ...
    def __or__(self, other): ...
    def skew(self, start: float = 1.0, stop: Incomplete | None = None, step: float = 1.0): ...
    def apply_async(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, add_to_parent: bool = True, producer: Incomplete | None = None, link: Incomplete | None = None, link_error: Incomplete | None = None, **options): ...
    def apply(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, **options): ...
    def set_immutable(self, immutable) -> None: ...
    def stamp(self, visitor: Incomplete | None = None, append_stamps: bool = False, **headers) -> None: ...
    def link(self, sig): ...
    def link_error(self, sig): ...
    def freeze(self, _id: Incomplete | None = None, group_id: Incomplete | None = None, chord: Incomplete | None = None, root_id: Incomplete | None = None, parent_id: Incomplete | None = None, group_index: Incomplete | None = None): ...
    def __len__(self) -> int: ...
    @property
    def app(self): ...

class _chord(Signature):
    @classmethod
    def from_dict(cls, d, app: Incomplete | None = None): ...
    subtask_type: str
    def __init__(self, header, body: Incomplete | None = None, task: str = 'celery.chord', args: Incomplete | None = None, kwargs: Incomplete | None = None, app: Incomplete | None = None, **options) -> None: ...
    def __call__(self, body: Incomplete | None = None, **options): ...
    def __or__(self, other): ...
    tasks: Incomplete
    id: Incomplete
    def freeze(self, _id: Incomplete | None = None, group_id: Incomplete | None = None, chord: Incomplete | None = None, root_id: Incomplete | None = None, parent_id: Incomplete | None = None, group_index: Incomplete | None = None): ...
    def stamp(self, visitor: Incomplete | None = None, append_stamps: bool = False, **headers) -> None: ...
    def apply_async(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, task_id: Incomplete | None = None, producer: Incomplete | None = None, publisher: Incomplete | None = None, connection: Incomplete | None = None, router: Incomplete | None = None, result_cls: Incomplete | None = None, **options): ...
    def apply(self, args: Incomplete | None = None, kwargs: Incomplete | None = None, propagate: bool = True, body: Incomplete | None = None, **options): ...
    def __length_hint__(self) -> int: ...
    def run(self, header, body, partial_args, app: Incomplete | None = None, interval: Incomplete | None = None, countdown: int = 1, max_retries: Incomplete | None = None, eager: bool = False, task_id: Incomplete | None = None, kwargs: Incomplete | None = None, **options): ...
    def clone(self, *args, **kwargs): ...
    def link(self, callback): ...
    def link_error(self, errback): ...
    def set_immutable(self, immutable) -> None: ...
    def app(self): ...
    body: Incomplete

chord: Incomplete

def signature(varies, *args, **kwargs): ...
subtask = signature

def maybe_signature(d, app: Incomplete | None = None, clone: bool = False): ...
maybe_subtask = maybe_signature
