from _typeshed import Incomplete
from billiard.exceptions import SoftTimeLimitExceeded as SoftTimeLimitExceeded, Terminated as Terminated, TimeLimitExceeded as TimeLimitExceeded, WorkerLostError as WorkerLostError
from click import ClickException
from kombu.exceptions import OperationalError as OperationalError

__all__ = ['reraise', 'CeleryWarning', 'AlwaysEagerIgnored', 'DuplicateNodenameWarning', 'FixupWarning', 'NotConfigured', 'SecurityWarning', 'CeleryError', 'ImproperlyConfigured', 'SecurityError', 'OperationalError', 'TaskPredicate', 'Ignore', 'Reject', 'Retry', 'TaskError', 'QueueNotFound', 'IncompleteStream', 'NotRegistered', 'AlreadyRegistered', 'TimeoutError', 'MaxRetriesExceededError', 'TaskRevokedError', 'InvalidTaskError', 'ChordError', 'BackendError', 'BackendGetMetaError', 'BackendStoreError', 'SoftTimeLimitExceeded', 'TimeLimitExceeded', 'WorkerLostError', 'Terminated', 'CPendingDeprecationWarning', 'CDeprecationWarning', 'WorkerShutdown', 'WorkerTerminate', 'CeleryCommandException']

def reraise(tp, value, tb: Incomplete | None = None) -> None: ...

class CeleryWarning(UserWarning): ...
class AlwaysEagerIgnored(CeleryWarning): ...
class DuplicateNodenameWarning(CeleryWarning): ...
class FixupWarning(CeleryWarning): ...
class NotConfigured(CeleryWarning): ...
class SecurityWarning(CeleryWarning): ...
class CeleryError(Exception): ...
class TaskPredicate(CeleryError): ...

class Retry(TaskPredicate):
    message: Incomplete
    exc: Incomplete
    when: Incomplete
    is_eager: Incomplete
    sig: Incomplete
    def __init__(self, message: Incomplete | None = None, exc: Incomplete | None = None, when: Incomplete | None = None, is_eager: bool = False, sig: Incomplete | None = None, **kwargs) -> None: ...
    def humanize(self): ...
    def __reduce__(self): ...
RetryTaskError = Retry

class Ignore(TaskPredicate): ...

class Reject(TaskPredicate):
    reason: Incomplete
    requeue: Incomplete
    def __init__(self, reason: Incomplete | None = None, requeue: bool = False) -> None: ...

class ImproperlyConfigured(CeleryError): ...
class SecurityError(CeleryError): ...
class TaskError(CeleryError): ...
class QueueNotFound(KeyError, TaskError): ...
class IncompleteStream(TaskError): ...
class NotRegistered(KeyError, TaskError): ...
class AlreadyRegistered(TaskError): ...
class TimeoutError(TaskError): ...

class MaxRetriesExceededError(TaskError):
    task_args: Incomplete
    task_kwargs: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...

class TaskRevokedError(TaskError): ...
class InvalidTaskError(TaskError): ...
class ChordError(TaskError): ...
class CPendingDeprecationWarning(PendingDeprecationWarning): ...
class CDeprecationWarning(DeprecationWarning): ...
class WorkerTerminate(SystemExit): ...
SystemTerminate = WorkerTerminate

class WorkerShutdown(SystemExit): ...
class BackendError(Exception): ...

class BackendGetMetaError(BackendError):
    task_id: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...

class BackendStoreError(BackendError):
    state: Incomplete
    task_id: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...

class CeleryCommandException(ClickException):
    exit_code: Incomplete
    def __init__(self, message, exit_code) -> None: ...
