from _typeshed import Incomplete
from types import ModuleType

__all__ = ['Proxy', 'PromiseProxy', 'try_import', 'maybe_evaluate']

def try_import(module, default: Incomplete | None = None): ...

class Proxy:
    def __init__(self, local, args: Incomplete | None = None, kwargs: Incomplete | None = None, name: Incomplete | None = None, __doc__: Incomplete | None = None) -> None: ...
    def __qualname__(self): ...
    def __module__(self): ...
    def __doc__(self): ...
    @property
    def __class__(self): ...
    @property
    def __dict__(self): ...
    def __bool__(self) -> bool: ...
    __nonzero__ = __bool__
    def __dir__(self): ...
    def __getattr__(self, name): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __setattr__(self, name, value) -> None: ...
    def __delattr__(self, name) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __hash__(self): ...
    def __call__(self, *a, **kw): ...
    def __len__(self) -> int: ...
    def __getitem__(self, i): ...
    def __iter__(self): ...
    def __contains__(self, i) -> bool: ...
    def __add__(self, other): ...
    def __sub__(self, other): ...
    def __mul__(self, other): ...
    def __floordiv__(self, other): ...
    def __mod__(self, other): ...
    def __divmod__(self, other): ...
    def __pow__(self, other): ...
    def __lshift__(self, other): ...
    def __rshift__(self, other): ...
    def __and__(self, other): ...
    def __xor__(self, other): ...
    def __or__(self, other): ...
    def __div__(self, other): ...
    def __truediv__(self, other): ...
    def __neg__(self): ...
    def __pos__(self): ...
    def __abs__(self): ...
    def __invert__(self): ...
    def __complex__(self) -> complex: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __oct__(self): ...
    def __hex__(self): ...
    def __index__(self) -> int: ...
    def __coerce__(self, other): ...
    def __enter__(self): ...
    def __exit__(self, *a, **kw): ...
    def __reduce__(self): ...

class PromiseProxy(Proxy):
    def __then__(self, fun, *args, **kwargs): ...
    def __evaluated__(self): ...
    def __maybe_evaluate__(self): ...
    def __evaluate__(self, _clean=('_Proxy__local', '_Proxy__args', '_Proxy__kwargs')): ...

def maybe_evaluate(obj): ...

class class_property:
    __doc__: Incomplete
    __module__: Incomplete
    def __init__(self, getter: Incomplete | None = None, setter: Incomplete | None = None) -> None: ...
    def __get__(self, obj, type: Incomplete | None = None): ...
    def __set__(self, obj, value): ...
    def setter(self, setter): ...

class LazyModule(ModuleType):
    def __getattr__(self, name): ...
    def __dir__(self): ...
    def __reduce__(self): ...
