from _typeshed import Incomplete
from billiard.compat import close_open_fds as close_open_fds, get_fdmax as get_fdmax
from collections.abc import Generator

__all__ = ['EX_OK', 'EX_FAILURE', 'EX_UNAVAILABLE', 'EX_USAGE', 'SYSTEM', 'IS_macOS', 'IS_WINDOWS', 'SIGMAP', 'pyimplementation', 'LockFailed', 'get_fdmax', 'Pidfile', 'create_pidlock', 'close_open_fds', 'DaemonContext', 'detached', 'parse_uid', 'parse_gid', 'setgroups', 'initgroups', 'setgid', 'setuid', 'maybe_drop_privileges', 'signals', 'signal_name', 'set_process_title', 'set_mp_process_title', 'get_errno_name', 'ignore_errno', 'fd_by_path']

EX_OK: Incomplete
EX_FAILURE: int
EX_UNAVAILABLE: Incomplete
EX_USAGE: Incomplete
SYSTEM: Incomplete
IS_macOS: Incomplete
IS_WINDOWS: Incomplete
SIGMAP: Incomplete

def pyimplementation(): ...

class LockFailed(Exception): ...

class Pidfile:
    path: Incomplete
    def __init__(self, path) -> None: ...
    def acquire(self): ...
    __enter__ = acquire
    def is_locked(self): ...
    def release(self, *args) -> None: ...
    __exit__ = release
    def read_pid(self): ...
    def remove(self) -> None: ...
    def remove_if_stale(self): ...
    def write_pid(self) -> None: ...
PIDFile = Pidfile

def create_pidlock(pidfile): ...
def fd_by_path(paths): ...

class DaemonContext:
    workdir: Incomplete
    umask: Incomplete
    fake: Incomplete
    after_chdir: Incomplete
    after_forkers: Incomplete
    stdfds: Incomplete
    def __init__(self, pidfile: Incomplete | None = None, workdir: Incomplete | None = None, umask: Incomplete | None = None, fake: bool = False, after_chdir: Incomplete | None = None, after_forkers: bool = True, **kwargs) -> None: ...
    def redirect_to_null(self, fd) -> None: ...
    def open(self) -> None: ...
    __enter__ = open
    def close(self, *args) -> None: ...
    __exit__ = close

def detached(logfile: Incomplete | None = None, pidfile: Incomplete | None = None, uid: Incomplete | None = None, gid: Incomplete | None = None, umask: int = 0, workdir: Incomplete | None = None, fake: bool = False, **opts): ...
def parse_uid(uid): ...
def parse_gid(gid): ...
def setgroups(groups): ...
def initgroups(uid, gid): ...
def setgid(gid) -> None: ...
def setuid(uid) -> None: ...
def maybe_drop_privileges(uid: Incomplete | None = None, gid: Incomplete | None = None) -> None: ...

class Signals:
    ignored: Incomplete
    default: Incomplete
    def arm_alarm(self, seconds): ...
    def reset_alarm(self): ...
    def supported(self, name): ...
    def signum(self, name): ...
    def reset(self, *signal_names) -> None: ...
    def ignore(self, *names) -> None: ...
    def __getitem__(self, name): ...
    def __setitem__(self, name, handler) -> None: ...
    def update(self, _d_: Incomplete | None = None, **sigmap) -> None: ...

signals: Incomplete

def signal_name(signum): ...
def set_process_title(progname, info: Incomplete | None = None): ...
def set_mp_process_title(*a, **k) -> None: ...
def get_errno_name(n): ...
def ignore_errno(*errnos, **kwargs) -> Generator[None]: ...
