import re
from _typeshed import Incomplete
from celery import Celery
from datetime import datetime, timedelta, tzinfo
from typing import Any, Callable, NamedTuple

__all__ = ['ParseException', 'schedule', 'crontab', 'crontab_parser', 'maybe_schedule', 'solar']

class schedstate(NamedTuple):
    is_due: Incomplete
    next: Incomplete

class ParseException(Exception): ...

class BaseSchedule:
    nowfun: Incomplete
    def __init__(self, nowfun: Callable | None = None, app: Celery | None = None) -> None: ...
    def now(self) -> datetime: ...
    def remaining_estimate(self, last_run_at: datetime) -> timedelta: ...
    def is_due(self, last_run_at: datetime) -> tuple[bool, datetime]: ...
    def maybe_make_aware(self, dt: datetime, naive_as_utc: bool = True) -> datetime: ...
    @property
    def app(self) -> Celery: ...
    @app.setter
    def app(self, app: Celery) -> None: ...
    def tz(self) -> tzinfo: ...
    def utc_enabled(self) -> bool: ...
    def to_local(self, dt: datetime) -> datetime: ...
    def __eq__(self, other: Any) -> bool: ...

class schedule(BaseSchedule):
    relative: bool
    run_every: Incomplete
    def __init__(self, run_every: float | timedelta | None = None, relative: bool = False, nowfun: Callable | None = None, app: Celery | None = None) -> None: ...
    def remaining_estimate(self, last_run_at: datetime) -> timedelta: ...
    def is_due(self, last_run_at: datetime) -> tuple[bool, datetime]: ...
    def __eq__(self, other: Any) -> bool: ...
    def __reduce__(self) -> tuple[type, tuple[timedelta, bool, Callable | None]]: ...
    @property
    def seconds(self) -> int | float: ...
    @property
    def human_seconds(self) -> str: ...

class crontab_parser:
    ParseException = ParseException
    max_: Incomplete
    min_: Incomplete
    pats: tuple[tuple[re.Pattern, Callable], ...]
    def __init__(self, max_: int = 60, min_: int = 0) -> None: ...
    def parse(self, spec: str) -> set[int]: ...

class crontab(BaseSchedule):
    hour: Incomplete
    minute: Incomplete
    day_of_week: Incomplete
    day_of_month: Incomplete
    month_of_year: Incomplete
    def __init__(self, minute: str = '*', hour: str = '*', day_of_week: str = '*', day_of_month: str = '*', month_of_year: str = '*', **kwargs: Any) -> None: ...
    def __reduce__(self) -> tuple[type, tuple[str, str, str, str, str], Any]: ...
    def remaining_delta(self, last_run_at: datetime, tz: tzinfo | None = None, ffwd: type = ...) -> tuple[datetime, Any, datetime]: ...
    def remaining_estimate(self, last_run_at: datetime, ffwd: type = ...) -> timedelta: ...
    def is_due(self, last_run_at: datetime) -> tuple[bool, datetime]: ...
    def __eq__(self, other: Any) -> bool: ...

def maybe_schedule(s: int | float | timedelta | BaseSchedule, relative: bool = False, app: Celery | None = None) -> float | timedelta | BaseSchedule: ...

class solar(BaseSchedule):
    ephem: Incomplete
    event: Incomplete
    lat: Incomplete
    lon: Incomplete
    cal: Incomplete
    method: Incomplete
    use_center: Incomplete
    def __init__(self, event: str, lat: int | float, lon: int | float, **kwargs: Any) -> None: ...
    def __reduce__(self) -> tuple[type, tuple[str, int | float, int | float]]: ...
    def remaining_estimate(self, last_run_at: datetime) -> timedelta: ...
    def is_due(self, last_run_at: datetime) -> tuple[bool, datetime]: ...
    def __eq__(self, other: Any) -> bool: ...
