# Generated by Django 5.1.6 on 2025-03-04 21:27

import apps.jobs.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='ID of the user who initiated the job')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('discarded', 'Discarded')], default='pending', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_file', models.FileField(upload_to=apps.jobs.models.job_directory_path)),
                ('gridfs_id', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, help_text='ID of the Celery task processing this job', max_length=50, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('processed_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('needs_review', models.BooleanField(default=False)),
                ('template_used', models.CharField(blank=True, help_text='ID of the template used for parsing', max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_started', models.DateTimeField(blank=True, null=True)),
                ('processing_completed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='jobs_proces_user_id_6f0783_idx'), models.Index(fields=['status'], name='jobs_proces_status_d38ef0_idx'), models.Index(fields=['task_id'], name='jobs_proces_task_id_17b42d_idx'), models.Index(fields=['created_at'], name='jobs_proces_created_bd9b15_idx')],
            },
        ),
    ]
