from _typeshed import Incomplete
from collections import UserList
from collections.abc import Generator

__all__ = ['Cluster', 'Node']

class NamespacedOptionParser:
    args: Incomplete
    options: Incomplete
    values: Incomplete
    passthrough: str
    namespaces: Incomplete
    def __init__(self, args) -> None: ...
    def parse(self) -> None: ...
    def process_long_opt(self, arg, value: Incomplete | None = None) -> None: ...
    def process_short_opt(self, arg, value: Incomplete | None = None) -> None: ...
    def optmerge(self, ns, defaults: Incomplete | None = None): ...
    def add_option(self, name, value, short: bool = False, ns: Incomplete | None = None) -> None: ...

class Node:
    name: Incomplete
    cmd: Incomplete
    append: Incomplete
    extra_args: Incomplete
    options: Incomplete
    expander: Incomplete
    argv: Incomplete
    def __init__(self, name, cmd: Incomplete | None = None, append: Incomplete | None = None, options: Incomplete | None = None, extra_args: Incomplete | None = None) -> None: ...
    def alive(self): ...
    def send(self, sig, on_error: Incomplete | None = None): ...
    def start(self, env: Incomplete | None = None, **kwargs): ...
    def handle_process_exit(self, retcode, on_signalled: Incomplete | None = None, on_failure: Incomplete | None = None): ...
    def prepare_argv(self, argv, path): ...
    def getopt(self, *alt): ...
    def pidfile(self): ...
    def logfile(self): ...
    @property
    def pid(self): ...
    @pid.setter
    def pid(self, value) -> None: ...
    def executable(self): ...
    def argv_with_executable(self): ...
    @classmethod
    def from_kwargs(cls, name, **kwargs): ...

class MultiParser:
    Node = Node
    cmd: Incomplete
    append: Incomplete
    prefix: Incomplete
    suffix: Incomplete
    range_prefix: Incomplete
    def __init__(self, cmd: str = 'celery worker', append: str = '', prefix: str = '', suffix: str = '', range_prefix: str = 'celery') -> None: ...
    def parse(self, p): ...

class Cluster(UserList):
    nodes: Incomplete
    cmd: Incomplete
    env: Incomplete
    on_stopping_preamble: Incomplete
    on_send_signal: Incomplete
    on_still_waiting_for: Incomplete
    on_still_waiting_progress: Incomplete
    on_still_waiting_end: Incomplete
    on_node_start: Incomplete
    on_node_restart: Incomplete
    on_node_shutdown_ok: Incomplete
    on_node_status: Incomplete
    on_node_signal: Incomplete
    on_node_signal_dead: Incomplete
    on_node_down: Incomplete
    on_child_spawn: Incomplete
    on_child_signalled: Incomplete
    on_child_failure: Incomplete
    def __init__(self, nodes, cmd: Incomplete | None = None, env: Incomplete | None = None, on_stopping_preamble: Incomplete | None = None, on_send_signal: Incomplete | None = None, on_still_waiting_for: Incomplete | None = None, on_still_waiting_progress: Incomplete | None = None, on_still_waiting_end: Incomplete | None = None, on_node_start: Incomplete | None = None, on_node_restart: Incomplete | None = None, on_node_shutdown_ok: Incomplete | None = None, on_node_status: Incomplete | None = None, on_node_signal: Incomplete | None = None, on_node_signal_dead: Incomplete | None = None, on_node_down: Incomplete | None = None, on_child_spawn: Incomplete | None = None, on_child_signalled: Incomplete | None = None, on_child_failure: Incomplete | None = None) -> None: ...
    def start(self): ...
    def start_node(self, node): ...
    def send_all(self, sig) -> None: ...
    def kill(self): ...
    def restart(self, sig=...): ...
    def stop(self, retry: Incomplete | None = None, callback: Incomplete | None = None, sig=...): ...
    def stopwait(self, retry: int = 2, callback: Incomplete | None = None, sig=...): ...
    def shutdown_nodes(self, nodes, sig=..., retry: Incomplete | None = None) -> Generator[Incomplete]: ...
    def find(self, name): ...
    def getpids(self, on_down: Incomplete | None = None) -> Generator[Incomplete]: ...
    @property
    def data(self): ...
