from _typeshed import Incomplete
from celery.worker import WorkController

__all__ = ['Worker']

class Worker(WorkController):
    quiet: Incomplete
    def on_before_init(self, quiet: bool = False, **kwargs) -> None: ...
    redirect_stdouts: Incomplete
    redirect_stdouts_level: Incomplete
    purge: Incomplete
    no_color: Incomplete
    colored: Incomplete
    def on_after_init(self, purge: bool = False, no_color: Incomplete | None = None, redirect_stdouts: Incomplete | None = None, redirect_stdouts_level: Incomplete | None = None, **kwargs) -> None: ...
    def on_init_blueprint(self) -> None: ...
    def on_start(self) -> None: ...
    def emit_banner(self) -> None: ...
    def on_consumer_ready(self, consumer) -> None: ...
    def setup_logging(self, colorize: Incomplete | None = None): ...
    def purge_messages(self) -> None: ...
    def tasklist(self, include_builtins: bool = True, sep: str = '\n', int_: str = 'celery.'): ...
    def extra_info(self): ...
    def startup_info(self, artlines: bool = True): ...
    def install_platform_tweaks(self, worker) -> None: ...
    def macOS_proxy_detection_workaround(self) -> None: ...
    def set_process_status(self, info): ...
