from _typeshed import Incomplete
from collections.abc import Generator

__all__ = ['AsyncBackendMixin', 'BaseResultConsumer', 'Drainer', 'register_drainer']

def register_drainer(name): ...

class Drainer:
    result_consumer: Incomplete
    def __init__(self, result_consumer) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def drain_events_until(self, p, timeout: Incomplete | None = None, interval: int = 1, on_interval: Incomplete | None = None, wait: Incomplete | None = None) -> Generator[Incomplete]: ...
    def wait_for(self, p, wait, timeout: Incomplete | None = None) -> None: ...

class greenletDrainer(Drainer):
    spawn: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def run(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def wait_for(self, p, wait, timeout: Incomplete | None = None) -> None: ...

class eventletDrainer(greenletDrainer):
    def spawn(self, func): ...

class geventDrainer(greenletDrainer):
    def spawn(self, func): ...

class AsyncBackendMixin:
    def iter_native(self, result, no_ack: bool = True, **kwargs) -> Generator[Incomplete]: ...
    def add_pending_result(self, result, weak: bool = False, start_drainer: bool = True): ...
    def add_pending_results(self, results, weak: bool = False): ...
    def remove_pending_result(self, result): ...
    def on_result_fulfilled(self, result) -> None: ...
    def wait_for_pending(self, result, callback: Incomplete | None = None, propagate: bool = True, **kwargs): ...
    @property
    def is_async(self): ...

class BaseResultConsumer:
    backend: Incomplete
    app: Incomplete
    accept: Incomplete
    on_message: Incomplete
    buckets: Incomplete
    drainer: Incomplete
    def __init__(self, backend, app, accept, pending_results, pending_messages) -> None: ...
    def start(self, initial_task_id, **kwargs) -> None: ...
    def stop(self) -> None: ...
    def drain_events(self, timeout: Incomplete | None = None) -> None: ...
    def consume_from(self, task_id) -> None: ...
    def cancel_for(self, task_id) -> None: ...
    def on_after_fork(self) -> None: ...
    def drain_events_until(self, p, timeout: Incomplete | None = None, on_interval: Incomplete | None = None): ...
    def on_wait_for_pending(self, result, timeout: Incomplete | None = None, **kwargs) -> None: ...
    def on_out_of_band_result(self, message) -> None: ...
    def on_state_change(self, meta, message) -> None: ...
