from .base import KeyValueStoreBackend
from _typeshed import Incomplete

__all__ = ['AzureBlockBlobBackend']

class AzureBlockBlobBackend(KeyValueStoreBackend):
    base_path: Incomplete
    def __init__(self, url: Incomplete | None = None, container_name: Incomplete | None = None, *args, **kwargs) -> None: ...
    def get(self, key): ...
    def set(self, key, value) -> None: ...
    def mget(self, keys): ...
    def delete(self, key) -> None: ...
    def as_uri(self, include_password: bool = False): ...
