from _typeshed import Incomplete
from celery.exceptions import TimeoutError
from collections.abc import Generator
from kombu.utils.encoding import ensure_bytes
from typing import NamedTuple

__all__ = ['BaseBackend', 'KeyValueStoreBackend', 'DisabledBackend']

class pending_results_t(NamedTuple):
    concrete: Incomplete
    weak: Incomplete

class _nulldict(dict):
    def ignore(self, *a, **kw) -> None: ...
    __setitem__ = ignore
    update = ignore
    setdefault = ignore

class Backend:
    READY_STATES: Incomplete
    UNREADY_STATES: Incomplete
    EXCEPTION_STATES: Incomplete
    TimeoutError = TimeoutError
    subpolling_interval: Incomplete
    supports_native_join: bool
    supports_autoexpire: bool
    persistent: bool
    retry_policy: Incomplete
    app: Incomplete
    serializer: Incomplete
    expires: Incomplete
    accept: Incomplete
    always_retry: Incomplete
    max_sleep_between_retries_ms: Incomplete
    base_sleep_between_retries_ms: Incomplete
    max_retries: Incomplete
    thread_safe: Incomplete
    url: Incomplete
    def __init__(self, app, serializer: Incomplete | None = None, max_cached_results: Incomplete | None = None, accept: Incomplete | None = None, expires: Incomplete | None = None, expires_type: Incomplete | None = None, url: Incomplete | None = None, **kwargs) -> None: ...
    def as_uri(self, include_password: bool = False): ...
    def mark_as_started(self, task_id, **meta): ...
    def mark_as_done(self, task_id, result, request: Incomplete | None = None, store_result: bool = True, state=...) -> None: ...
    def mark_as_failure(self, task_id, exc, traceback: Incomplete | None = None, request: Incomplete | None = None, store_result: bool = True, call_errbacks: bool = True, state=...) -> None: ...
    def mark_as_revoked(self, task_id, reason: str = '', request: Incomplete | None = None, store_result: bool = True, state=...) -> None: ...
    def mark_as_retry(self, task_id, exc, traceback: Incomplete | None = None, request: Incomplete | None = None, store_result: bool = True, state=...): ...
    def chord_error_from_stack(self, callback, exc: Incomplete | None = None): ...
    def fail_from_current_stack(self, task_id, exc: Incomplete | None = None): ...
    def prepare_exception(self, exc, serializer: Incomplete | None = None): ...
    def exception_to_python(self, exc): ...
    def prepare_value(self, result): ...
    def encode(self, data): ...
    def meta_from_decoded(self, meta): ...
    def decode_result(self, payload): ...
    def decode(self, payload): ...
    def prepare_expires(self, value, type: Incomplete | None = None): ...
    def prepare_persistent(self, enabled: Incomplete | None = None): ...
    def encode_result(self, result, state): ...
    def is_cached(self, task_id): ...
    def store_result(self, task_id, result, state, traceback: Incomplete | None = None, request: Incomplete | None = None, **kwargs): ...
    def forget(self, task_id) -> None: ...
    def get_state(self, task_id): ...
    get_status = get_state
    def get_traceback(self, task_id): ...
    def get_result(self, task_id): ...
    def get_children(self, task_id): ...
    def exception_safe_to_retry(self, exc): ...
    def get_task_meta(self, task_id, cache: bool = True): ...
    def reload_task_result(self, task_id) -> None: ...
    def reload_group_result(self, group_id) -> None: ...
    def get_group_meta(self, group_id, cache: bool = True): ...
    def restore_group(self, group_id, cache: bool = True): ...
    def save_group(self, group_id, result): ...
    def delete_group(self, group_id): ...
    def cleanup(self) -> None: ...
    def process_cleanup(self) -> None: ...
    def on_task_call(self, producer, task_id): ...
    def add_to_chord(self, chord_id, result) -> None: ...
    def on_chord_part_return(self, request, state, result, **kwargs) -> None: ...
    def set_chord_size(self, group_id, chord_size) -> None: ...
    def fallback_chord_unlock(self, header_result, body, countdown: int = 1, **kwargs) -> None: ...
    def ensure_chords_allowed(self) -> None: ...
    def apply_chord(self, header_result_args, body, **kwargs) -> None: ...
    def current_task_children(self, request: Incomplete | None = None): ...
    def __reduce__(self, args=(), kwargs: Incomplete | None = None): ...

class SyncBackendMixin:
    def iter_native(self, result, timeout: Incomplete | None = None, interval: float = 0.5, no_ack: bool = True, on_message: Incomplete | None = None, on_interval: Incomplete | None = None) -> Generator[Incomplete, Incomplete]: ...
    def wait_for_pending(self, result, timeout: Incomplete | None = None, interval: float = 0.5, no_ack: bool = True, on_message: Incomplete | None = None, on_interval: Incomplete | None = None, callback: Incomplete | None = None, propagate: bool = True): ...
    def wait_for(self, task_id, timeout: Incomplete | None = None, interval: float = 0.5, no_ack: bool = True, on_interval: Incomplete | None = None): ...
    def add_pending_result(self, result, weak: bool = False): ...
    def remove_pending_result(self, result): ...
    @property
    def is_async(self): ...

class BaseBackend(Backend, SyncBackendMixin): ...
BaseDictBackend = BaseBackend

class BaseKeyValueStoreBackend(Backend):
    key_t = ensure_bytes
    task_keyprefix: str
    group_keyprefix: str
    chord_keyprefix: str
    implements_incr: bool
    apply_chord: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get(self, key) -> None: ...
    def mget(self, keys) -> None: ...
    def set(self, key, value) -> None: ...
    def delete(self, key) -> None: ...
    def incr(self, key) -> None: ...
    def expire(self, key, value) -> None: ...
    def get_key_for_task(self, task_id, key: str = ''): ...
    def get_key_for_group(self, group_id, key: str = ''): ...
    def get_key_for_chord(self, group_id, key: str = ''): ...
    def get_many(self, task_ids, timeout: Incomplete | None = None, interval: float = 0.5, no_ack: bool = True, on_message: Incomplete | None = None, on_interval: Incomplete | None = None, max_iterations: Incomplete | None = None, READY_STATES=...) -> Generator[Incomplete]: ...
    def on_chord_part_return(self, request, state, result, **kwargs): ...

class KeyValueStoreBackend(BaseKeyValueStoreBackend, SyncBackendMixin): ...

class DisabledBackend(BaseBackend):
    def store_result(self, *args, **kwargs) -> None: ...
    def ensure_chords_allowed(self) -> None: ...
    def as_uri(self, *args, **kwargs): ...
    get_state: Incomplete
    get_status: Incomplete
    get_result: Incomplete
    get_traceback: Incomplete
    get_task_meta_for: Incomplete
    wait_for: Incomplete
    get_many: Incomplete
