from .base import KeyValueStoreBackend
from _typeshed import Incomplete

__all__ = ['CacheBackend']

class DummyClient:
    cache: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get(self, key, *args, **kwargs): ...
    def get_multi(self, keys): ...
    def set(self, key, value, *args, **kwargs) -> None: ...
    def delete(self, key, *args, **kwargs) -> None: ...
    def incr(self, key, delta: int = 1): ...
    def touch(self, key, expire) -> None: ...

class CacheBackend(KeyValueStoreBackend):
    servers: Incomplete
    supports_autoexpire: bool
    supports_native_join: bool
    implements_incr: bool
    url: Incomplete
    options: Incomplete
    backend: Incomplete
    expires: Incomplete
    def __init__(self, app, expires: Incomplete | None = None, backend: Incomplete | None = None, options: Incomplete | None = None, url: Incomplete | None = None, **kwargs) -> None: ...
    def get(self, key): ...
    def mget(self, keys): ...
    def set(self, key, value): ...
    def delete(self, key): ...
    def incr(self, key): ...
    def expire(self, key, value): ...
    def client(self): ...
    def __reduce__(self, args=(), kwargs: Incomplete | None = None): ...
    def as_uri(self, *args, **kwargs): ...
