from .base import KeyValueStoreBackend
from _typeshed import Incomplete

__all__ = ['CosmosDBSQLBackend']

class CosmosDBSQLBackend(KeyValueStoreBackend):
    def __init__(self, url: Incomplete | None = None, database_name: Incomplete | None = None, collection_name: Incomplete | None = None, consistency_level: Incomplete | None = None, max_retry_attempts: Incomplete | None = None, max_retry_wait_time: Incomplete | None = None, *args, **kwargs) -> None: ...
    def get(self, key): ...
    def set(self, key, value) -> None: ...
    def mget(self, keys): ...
    def delete(self, key) -> None: ...
