from .base import KeyValueStoreBackend
from _typeshed import Incomplete

__all__ = ['ElasticsearchBackend']

class ElasticsearchBackend(KeyValueStoreBackend):
    index: str
    doc_type: Incomplete
    scheme: str
    host: str
    port: int
    username: Incomplete
    password: Incomplete
    es_retry_on_timeout: bool
    es_timeout: int
    es_max_retries: int
    url: Incomplete
    es_save_meta_as_text: Incomplete
    def __init__(self, url: Incomplete | None = None, *args, **kwargs) -> None: ...
    def exception_safe_to_retry(self, exc): ...
    def get(self, key): ...
    def set(self, key, value): ...
    def encode(self, data): ...
    def decode(self, payload): ...
    def mget(self, keys): ...
    def delete(self, key) -> None: ...
    @property
    def server(self): ...
