from .base import KeyValueStoreBackend
from _typeshed import Incomplete

__all__ = ['GCSBackend']

class GCSBackend(KeyValueStoreBackend):
    bucket_name: Incomplete
    project: Incomplete
    base_path: Incomplete
    ttl: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def get(self, key): ...
    def set(self, key, value) -> None: ...
    def delete(self, key) -> None: ...
    def mget(self, keys): ...
    @property
    def client(self): ...
    @property
    def bucket(self): ...
