from .base import BaseBackend
from _typeshed import Incomplete

__all__ = ['MongoBackend']

class InvalidDocument(Exception): ...

class MongoBackend(BaseBackend):
    mongo_host: Incomplete
    host: str
    port: int
    user: Incomplete
    password: Incomplete
    database_name: str
    taskmeta_collection: str
    groupmeta_collection: str
    max_pool_size: int
    options: Incomplete
    supports_autoexpire: bool
    url: Incomplete
    def __init__(self, app: Incomplete | None = None, **kwargs) -> None: ...
    def encode(self, data): ...
    def decode(self, data): ...
    def cleanup(self) -> None: ...
    def __reduce__(self, args=(), kwargs: Incomplete | None = None): ...
    def database(self): ...
    def collection(self): ...
    def group_collection(self): ...
    def expires_delta(self): ...
    def as_uri(self, include_password: bool = False): ...
