import redis
import redis.sentinel
from .asynchronous import AsyncBackendMixin, BaseResultConsumer
from .base import BaseKeyValueStoreBackend
from _typeshed import Incomplete
from collections.abc import Generator

__all__ = ['RedisBackend', 'SentinelBackend']

class ResultConsumer(BaseResultConsumer):
    subscribed_to: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def on_after_fork(self) -> None: ...
    def reconnect_on_error(self) -> Generator[None]: ...
    def on_state_change(self, meta, message) -> None: ...
    def start(self, initial_task_id, **kwargs) -> None: ...
    def on_wait_for_pending(self, result, **kwargs) -> None: ...
    def stop(self) -> None: ...
    def drain_events(self, timeout: Incomplete | None = None) -> None: ...
    def consume_from(self, task_id): ...
    def cancel_for(self, task_id) -> None: ...

class RedisBackend(BaseKeyValueStoreBackend, AsyncBackendMixin):
    ResultConsumer = ResultConsumer
    redis = redis
    connection_class_ssl: Incomplete
    max_connections: Incomplete
    supports_autoexpire: bool
    supports_native_join: bool
    connparams: Incomplete
    url: Incomplete
    result_consumer: Incomplete
    def __init__(self, host: Incomplete | None = None, port: Incomplete | None = None, db: Incomplete | None = None, password: Incomplete | None = None, max_connections: Incomplete | None = None, url: Incomplete | None = None, connection_pool: Incomplete | None = None, **kwargs) -> None: ...
    def retry_policy(self): ...
    def on_task_call(self, producer, task_id) -> None: ...
    def get(self, key): ...
    def mget(self, keys): ...
    def ensure(self, fun, args, **policy): ...
    def on_connection_error(self, max_retries, exc, intervals, retries): ...
    def set(self, key, value, **retry_policy): ...
    def forget(self, task_id) -> None: ...
    def delete(self, key) -> None: ...
    def incr(self, key): ...
    def expire(self, key, value): ...
    def add_to_chord(self, group_id, result) -> None: ...
    def set_chord_size(self, group_id, chord_size) -> None: ...
    def apply_chord(self, header_result_args, body, **kwargs) -> None: ...
    def on_chord_part_return(self, request, state, result, propagate: Incomplete | None = None, **kwargs): ...
    @property
    def ConnectionPool(self): ...
    def client(self): ...
    def __reduce__(self, args=(), kwargs: Incomplete | None = None): ...

class SentinelManagedSSLConnection(redis.sentinel.SentinelManagedConnection, redis.SSLConnection): ...

class SentinelBackend(RedisBackend):
    sentinel: Incomplete
    connection_class_ssl: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def as_uri(self, include_password: bool = False): ...
