import kombu
from . import base
from .asynchronous import AsyncBackendMixin, BaseResultConsumer
from _typeshed import Incomplete

__all__ = ['BacklogLimitExceeded', 'RPCBackend']

class BacklogLimitExceeded(Exception): ...

class ResultConsumer(BaseResultConsumer):
    Consumer: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def start(self, initial_task_id, no_ack: bool = True, **kwargs) -> None: ...
    def drain_events(self, timeout: Incomplete | None = None): ...
    def stop(self) -> None: ...
    def on_after_fork(self) -> None: ...
    def consume_from(self, task_id): ...
    def cancel_for(self, task_id) -> None: ...

class RPCBackend(base.Backend, AsyncBackendMixin):
    Exchange: Incomplete
    Producer: Incomplete
    ResultConsumer = ResultConsumer
    BacklogLimitExceeded = BacklogLimitExceeded
    persistent: bool
    supports_autoexpire: bool
    supports_native_join: bool
    retry_policy: Incomplete
    class Consumer(kombu.Consumer):
        auto_declare: bool
    class Queue(kombu.Queue):
        can_cache_declaration: bool
    delivery_mode: Incomplete
    exchange: Incomplete
    serializer: Incomplete
    auto_delete: Incomplete
    result_consumer: Incomplete
    def __init__(self, app, connection: Incomplete | None = None, exchange: Incomplete | None = None, exchange_type: Incomplete | None = None, persistent: Incomplete | None = None, serializer: Incomplete | None = None, auto_delete: bool = True, **kwargs) -> None: ...
    def ensure_chords_allowed(self) -> None: ...
    def on_task_call(self, producer, task_id) -> None: ...
    def destination_for(self, task_id, request): ...
    def on_reply_declare(self, task_id) -> None: ...
    def on_result_fulfilled(self, result) -> None: ...
    def as_uri(self, include_password: bool = True): ...
    def store_result(self, task_id, result, state, traceback: Incomplete | None = None, request: Incomplete | None = None, **kwargs): ...
    def on_out_of_band_result(self, task_id, message) -> None: ...
    def get_task_meta(self, task_id, backlog_limit: int = 1000): ...
    poll = get_task_meta
    def revive(self, channel) -> None: ...
    def reload_task_result(self, task_id) -> None: ...
    def reload_group_result(self, task_id) -> None: ...
    def save_group(self, group_id, result) -> None: ...
    def restore_group(self, group_id, cache: bool = True) -> None: ...
    def delete_group(self, group_id) -> None: ...
    def __reduce__(self, args=(), kwargs: Incomplete | None = None): ...
    @property
    def binding(self): ...
    def oid(self): ...
