# Generated by Django 4.2.19 on 2025-03-05 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_jti", models.CharField(max_length=255, unique=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "blacklisted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "blacklisted_tokens",
                "indexes": [
                    models.Index(
                        fields=["token_jti"], name="blacklisted_token_j_36f8ca_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="blacklisted_user_id_a5837f_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="blacklisted_expires_d1bb66_idx"
                    ),
                ],
            },
        ),
    ]
